"""Restored-defect controls for private capability experience; exact source seams."""
NEW_CONTROLS = [('animal-owner-authentication',
  [('cog', 'if not canonical or not sameData(canonical, receipt) then', 'if not canonical then')],
  'animal_owner_authentication'),
 ('animal-zero-consumption',
  [('model', 'e.consumedAmount>0 and e.consumedAmount<=1000000000', 'e.consumedAmount>=0 and e.consumedAmount<=1000000000')],
  'animal_zero_consumption_refused'),
 ('legacy-rejected',
  [('model', '(state.version==VERSION[id] or state.version==PREVIOUS_VERSION[id])', 'state.version==VERSION[id]')],
  'legacy_read_supported'),
 ('migration-missing',
  [('model', 'state.version=VERSION[modelId]', 'state.version=state.version')],
  'legacy_observation_migrates'),
 ('frozen-provenance-rewritten',
  [('cog',
    'if good then s.models = updated end',
    'if good then s.models = updated; for _,e in ipairs(s.episodes) do for _,p in ipairs(e.proposals) do '
    'p.version=updated[p.modelId].version end end end')],
  'frozen_provenance_preserved'),
 ('dose-hidden-family',
  [('model', 'occurredAtHours=true, stats=true', 'family=true, occurredAtHours=true, stats=true'),
   ('cog',
    'x.itemId, x.itemType = receipt.itemId, receipt.itemType\n    -- family/profile/dose efficacy',
    'x.itemId, x.itemType = receipt.itemId, receipt.itemType; x.family=receipt.family\n    -- family/profile/dose efficacy')],
  'medication_private_projection'),
 ('dose-implies-efficacy',
  [('model',
    'elseif e.kind=="medication-use" then',
    'elseif e.kind=="medication-use" then remember(state,"goal:food","assumed efficacy",true,e)')],
  'legacy_beliefs_preserved'),
 ('extended-settles-episode',
  [('cog',
    'local function matchIntent(e, x)',
    'local function matchIntent(e, x)\n    if EXTENDED[x.kind] then return true end')],
  'dose_does_not_settle_episode'),
 ('dose-unconsumed',
  [('cog', 'or receipt.status ~= "completed" or receipt.consumed ~= 1', 'or receipt.status ~= "completed"')],
  'dose_requires_actual_use_consumed'),
 ('physical-occurrence-as-acquisition',
  [('cog', 'receipt.observedAtHours, receipt.atHours)', 'receipt.atHours, receipt.atHours)')],
  'physical_acquisition_clock'),
 ('physical-hidden-exposures',
  [('model', 'occurredAtHours=true, stats=true', 'exposures=true, occurredAtHours=true, stats=true'),
   ('cog',
    'x.stats = detached(receipt.stats)',
    'x.stats = detached(receipt.stats); x.exposures=detached(receipt.exposures)')],
  'physical_private_projection'),
 ('physical-need-credit',
  [('model',
    'if e.kind=="physical-change" then\n        -- Numeric',
    'if e.kind=="physical-change" then\n'
    '        remember(state,"goal:water","assumed relief",true,e)\n'
    '        -- Numeric')],
  'physical_no_goal_or_episode_credit'),
 ('physical-old-aging',
  [('model',
    'local values=e.stats[name]',
    'e.worldHours=e.occurredAtHours\n            local values=e.stats[name]')],
  'physical_receipts_age_at_acquisition'),
 ('causal-gap-omitted', [('model', 'if depth>1 and physical then', 'if false then')], 'causal_gap_explicit'),
 ('reversal-not-revised',
  [('model', 'if state.beliefs["relation:vary:body:"..into..opposite] then', 'if false then')],
  'reversal_refines_same_record'),
 ('unchanged-feelings',
  [('model', 'or value.before==value.after then return false end', 'then return false end')],
  'physical_refuses_unchanged'),
 ('unknown-stat',
  [('model',
    'if not STAT_KEYS[name] or not plainKeys(value,{before=true,after=true})',
    'if not plainKeys(value,{before=true,after=true})')],
  'physical_refuses_unknown'),
 ('private-other-body',
  [('model',
    'if e.perspective~="performed" or e.actorId~=e.observerId\n            or e.foodPresent',
    'if e.foodPresent')],
  'other_body_changes_private'),
 ('preparation-eating-credit',
  [('model',
    'else relation(state,"transform","food","thermally-prepared-food",true,e,"manufacturing") end',
    'else relation(state,"transform","food","thermally-prepared-food",true,e,"manufacturing"); '
    'remember(state,"goal:food","assumed eating",true,e) end')],
  'preparation_is_not_eating'),
 ('preparation-wrong-receipt',
  [('cog', 'or receipt.nativeCredit ~= receipt.id or receipt.retrieved ~= true', 'or receipt.retrieved ~= true')],
  'preparation_refuses_credit'),
 ('preparation-no-heat',
  [('cog', 'or receipt.retrieved ~= true or receipt.heatObserved ~= true', 'or receipt.retrieved ~= true')],
  'preparation_refuses_heat'),
 ('preparation-no-progress',
  [('model', 'e.afterCookingTime>e.beforeCookingTime', 'e.afterCookingTime>=e.beforeCookingTime')],
  'preparation_refuses_progress'),
 ('preparation-not-retrieved',
  [('cog', 'or receipt.retrieved ~= true or receipt.heatObserved ~= true', 'or receipt.heatObserved ~= true')],
  'preparation_refuses_retrieved'),
 ('preparation-id-alias',
  [('cog', 'or receipt.id ~= "cooking/" .. tostring(id) .. "/" .. tostring(receipt.sequence)', 'or false')],
  'preparation_refuses_sequence'),
 ('preparation-association-absent',
  [('model',
    'else relation(state,"transform","food","thermally-prepared-food",true,e,"manufacturing") end',
    'end')],
  'independent_preparation_memory'),
 ('callback-reacquisition',
  [('cog', 'if prior and position <= prior then', 'if false then')],
  'dose_repeat_is_inert'),
 ('invalid-callback-allocation',
  [('cog', 'if not experienceCopy(id, x, clock() or -1) then return false, "invalid-experience" end', '')],
  'invalid_callback_does_not_allocate'),
 ('ledger-old-time-frontier',
  [('cog', 'if not EXTENDED[x.kind] then', 'if true then')],
  'batch_same_acquisition_258'),
 ('model-old-time-frontier', [('model', 'if not position then', 'if true then')], 'batch_same_acquisition_258'),
 ('model-evicted-occurrence',
  [('model', 'if previousPosition and position<=previousPosition then return "ignored:native-receipt" end', '')],
  'model_old_native_receipt_ordinary'),
 ('native-capability-context-omitted',
  [('cog', 'x.capabilities = C.capabilities(id)', 'x.capabilities = nil')],
  'context_first_private_medication'),
 ('native-replay-refreshes-context',
  [('cog', 'x.capabilities = detached(retained.capabilities)', 'x.capabilities = C.capabilities(id)')],
  'context_repeat_admitted_medication'),
 ('native-new-context-stale',
  [('cog', 'x.capabilities = C.capabilities(id)',
    'x.capabilities = s and detached(s.models.associative.capabilities) or C.capabilities(id)')],
  'context_new_private_medication')]
