import java.nio.*;import java.nio.file.*;import java.lang.reflect.*;import java.util.*;
import zombie.Lua.*;import zombie.iso.*;import zombie.GameTime;import zombie.characters.WornItems.*;import zombie.inventory.*;import zombie.scripting.objects.ItemBodyLocation;
import se.krka.kahlua.converter.KahluaConverterManager;import se.krka.kahlua.integration.LuaCaller;import se.krka.kahlua.j2se.J2SEPlatform;import se.krka.kahlua.luaj.compiler.LuaCompiler;import se.krka.kahlua.vm.*;
/** Native light/cell stack, IsoObject moddata/save and WornItems; UI/scene/body host controlled. */
public final class StateProbe {
 static J2SEPlatform p=J2SEPlatform.getInstance();static KahluaTable env;static IsoCell cell;static Stack<IsoLightSource> lamps=new Stack<>();static Map<String,KahluaTable> items=new HashMap<>();static IdentityHashMap<KahluaTable,InventoryItem> nativeItems=new IdentityHashMap<>();
 static KahluaTable item(String key){return items.computeIfAbsent(key,k->{var actual=new InventoryItem("Base",k,k,"Item_None");var t=p.newTable();nativeItems.put(t,actual);t.rawset("getBodyLocation",(JavaFunction)(f,n)->f.push("Makeup"));t.rawset("getName",(JavaFunction)(f,n)->f.push(k));return t;});}
 static ItemBodyLocation location;
 static KahluaTable wearer(String id){var group=BodyLocations.getGroup("Human");if(location==null)location=ItemBodyLocation.register("sao_proof:Makeup");group.getOrCreateLocation(location);var worn=new WornItems(group);var t=p.newTable();t.rawset("id",id);t.rawset("getWornItem",(JavaFunction)(f,n)->{var v=worn.getItem(location);for(var row:nativeItems.entrySet())if(row.getValue()==v)return f.push(row.getKey());return f.push(null);});t.rawset("setWornItem",(JavaFunction)(f,n)->{worn.setItem(location,nativeItems.get((KahluaTable)f.get(2)));return 0;});t.rawset("removeWornItem",(JavaFunction)(f,n)->{worn.remove(nativeItems.get((KahluaTable)f.get(1)));return 0;});t.rawset("nativeWornCount",(JavaFunction)(f,n)->f.push((double)worn.size()));t.rawset("resetModel",(JavaFunction)(f,n)->0);return t;}
 static LuaClosure findPreview(Object v,Set<Object>seen){if(v==null||!seen.add(v))return null;if(v instanceof LuaClosure c){if(c.prototype.numParams==7&&Arrays.stream(c.prototype.lines).anyMatch(x->x>=490&&x<580))return c;for(var u:c.upvalues){var found=findPreview(u.getValue(),seen);if(found!=null)return found;}}else if(v instanceof KahluaTable t){var it=t.iterator();while(it.advance()){var found=findPreview(it.getValue(),seen);if(found!=null)return found;}}return null;}
 public static void main(String[]args)throws Exception{
  env=p.newEnvironment();var thread=new KahluaThread(p,env);thread.debugOwnerThread=Thread.currentThread();LuaManager.env=env;LuaManager.thread=thread;GameTime.setInstance(new GameTime());zombie.ZomboidFileSystem.instance.base.set(new java.io.File("."));
  var unsafeField=sun.misc.Unsafe.class.getDeclaredField("theUnsafe");unsafeField.setAccessible(true);var unsafe=(sun.misc.Unsafe)unsafeField.get(null);cell=(IsoCell)unsafe.allocateInstance(IsoCell.class);var field=IsoCell.class.getDeclaredField("lamppostPositions");field.setAccessible(true);field.set(cell,lamps);
  var nativeCell=p.newTable();var list=p.newTable();list.rawset("contains",(JavaFunction)(f,n)->f.push(lamps.contains(f.get(1))));nativeCell.rawset("getLamppostPositions",(JavaFunction)(f,n)->f.push(list));nativeCell.rawset("addLamppost",(JavaFunction)(f,n)->{cell.addLamppost((IsoLightSource)f.get(1));return 0;});nativeCell.rawset("removeLamppost",(JavaFunction)(f,n)->{cell.removeLamppost((IsoLightSource)f.get(1));return 0;});env.rawset("NATIVE_CELL",nativeCell);
  env.rawset("nativeLight",(JavaFunction)(f,n)->f.push(new IsoLightSource(((Number)f.get(0)).intValue(),((Number)f.get(1)).intValue(),((Number)f.get(2)).intValue(),((Number)f.get(3)).floatValue(),((Number)f.get(4)).floatValue(),((Number)f.get(5)).floatValue(),((Number)f.get(6)).intValue())));
  env.rawset("nativeLampCount",(JavaFunction)(f,n)->f.push((double)lamps.stream().filter(l->l.life!=0).count()));env.rawset("nativeDiscardCellLights",(JavaFunction)(f,n)->{lamps.clear();return 0;});
  env.rawset("nativeData",(JavaFunction)(f,n)->f.push(new IsoObject().getModData()));env.rawset("nativeSaveLoad",(JavaFunction)(f,n)->{try{var buf=ByteBuffer.allocate(8192);((KahluaTable)f.get(0)).save(buf);buf.flip();var fresh=p.newTable();fresh.load(buf,240);return f.push(fresh);}catch(java.io.IOException e){throw new RuntimeException(e);}});
  env.rawset("nativeMakeup",(JavaFunction)(f,n)->f.push(item((String)f.get(0))));env.rawset("nativeWearer",(JavaFunction)(f,n)->f.push(wearer((String)f.get(0))));
  env.rawset("nativeBindPreview",(JavaFunction)(f,n)->{var c=findPreview(env.rawget("LSMirrorMenu"),Collections.newSetFromMap(new IdentityHashMap<>()));if(c==null)throw new AssertionError("no exact native compiled preview closure");for(var u:c.upvalues)if(u.getValue() instanceof KahluaTable t&&t.isEmpty()){for(int i=1;i<=8;i++){var s=p.newTable();s.rawset("setDirection",(JavaFunction)(q,z)->0);s.rawset("setZoom",(JavaFunction)(q,z)->0);s.rawset("setYOffset",(JavaFunction)(q,z)->0);s.rawset("setVisible",(JavaFunction)(q,z)->0);s.rawset("setEnable",(JavaFunction)(q,z)->0);s.rawset("setOnClick",(JavaFunction)(q,z)->0);s.rawset("setCharacter",(JavaFunction)(q,z)->{var callback=env.rawget("INTERLEAVE");if(callback instanceof LuaClosure fn){env.rawset("INTERLEAVE",null);thread.call(fn,null,null,null);}return 0;});t.rawset((double)i,s);}}return f.push(c);});
  var e=new Event("OnClientCommand",0);var events=p.newTable();e.register(p,events);new Event("OnInitGlobalModData",1).register(p,events);env.rawset("Events",events);var caller=new LuaCaller(new KahluaConverterManager());env.rawset("emitServer",(JavaFunction)(f,n)->{e.trigger(env,caller,new Object[]{"LS",f.get(0),f.get(1),f.get(2)});return 0;});env.rawset("MODE",args[0]);
  for(int i=1;i<args.length;i++)try(var in=Files.newBufferedReader(Path.of(args[i]))){thread.call(LuaCompiler.loadis(in,args[i],env),null,null,null);}
  if(!Boolean.TRUE.equals(env.rawget("PROVEN")))throw new AssertionError("no state proof");System.out.println("PASS state mode="+args[0]+" checks="+env.rawget("CHECKS"));
 }
}
