local count=0
local function check(name,value)if not value then error('D2_RADIO:'..name)end;count=count+1;print('CHECK '..name)end
local R=SAO.LeisureRadio
local function offer(activity,channel)
 for _,row in ipairs(R.offers('person',__body))do if (not activity or row.activity==activity)and(not channel or row.channel==channel)then return row end end
end
local function begin(activity,channel)local row=offer(activity,channel);assert(row,'missing offer');local ok,why=R.begin('person',__body,row,'purpose');assert(ok,tostring(why)..':'..tostring(__records.person.leisureRadioWork and __records.person.leisureRadioWork.reason));return R.work('person')end
local function outcome()local w=__records.person.leisureRadioWork;return R.outcome('person',w.sequence)end
__fresh();check('carried_current_and_native_preset_offers',#R.offers('person',__body)==2)
__familiar=false;check('no_universal_radio_knowledge',#R.offers('person',__body)==0)
__fresh();local foreign={}for k,v in pairs(__body)do foreign[k]=v end
check('foreign_body_refused',#R.offers('person',foreign)==0)
__fresh();local o=offer();o.channel=12345;check('spoof_offer_refused',not R.begin('person',__body,o,'purpose'))
__fresh();__admit=false;check('planner_refused_before_receiver',not R.begin('person',__body,offer(),'purpose')and __registers==0 and #__queue==0)
__fresh();__sourceDrift=true;check('changed_source_refused',not R.begin('person',__body,offer(),'purpose'))
__fresh();__registerAllowed=false;check('native_receiver_registration_refusal',not R.begin('person',__body,offer(),'purpose')and #__queue==0)
__fresh();local w=begin();R.advance('person',__body);check('admission_does_not_mean_hearing',not outcome()and __stats:get(CharacterStat.BOREDOM)==40)
__emit('BOR-1,UHP-2','guid:source');R.advance('person',__body)
check('original_source_real_stats_and_guid',__stats:get(CharacterStat.BOREDOM)==35 and __stats:get(CharacterStat.UNHAPPINESS)==20 and __known['guid:source'])
check('completion_one_heard_line',outcome().status=='completed'and outcome().participationUnit=='one-native-heard-line'and outcome().nativeProgress.heardLines==1)
check('no_public_device_stop_on_completion',__on and __unregisters==1 and __consumed==1)
local detached=outcome();detached.status='spoof';check('detached_outcome',outcome().status=='completed')
check('terminal_duplicate_does_not_reapply',not R.advance('person',__body)and __stats:get(CharacterStat.BOREDOM)==35)
__fresh();begin();__eventCurrent=false;__emit();R.advance('person',__body)
check('expired_native_emission_refused',outcome().status=='interrupted'and __stats:get(CharacterStat.BOREDOM)==40 and not __known['guid:line'])
__fresh();begin();__emit(nil,nil,{workId='foreign'});R.advance('person',__body)
check('foreign_work_event_refused',outcome().status=='interrupted'and __stats:get(CharacterStat.BOREDOM)==40)
__fresh();begin();__emit(nil,nil,{atHours=9});R.advance('person',__body)
check('preadmission_content_refused',outcome().status=='interrupted'and __stats:get(CharacterStat.BOREDOM)==40)
__fresh();__hours=1012;__nativeHours=12;begin();__hours=1012.1;__nativeHours=12.1;__emit();R.advance('person',__body)
check('county_offset_preserves_emission_clock',outcome().status=='completed'and outcome().nativeProgress.nativeEmission.atHours>1012
 and outcome().nativeProgress.nativeEmission.engineAtHours==12.1)
__fresh();__hours=1012;__nativeHours=12;begin();__nativeHours=11;__emit();R.advance('person',__body)
check('engine_clock_regression_refuses_receipt',outcome().status=='interrupted'and not __known['guid:line'])
__fresh();begin();__emit(nil,nil,{channel=99000});R.advance('person',__body)
check('foreign_channel_event_refused',outcome().status=='interrupted'and __stats:get(CharacterStat.BOREDOM)==40)
__fresh();begin();__emit(nil,nil,{mediaIndex=99});R.advance('person',__body)
check('foreign_media_event_refused',outcome().status=='interrupted'and __stats:get(CharacterStat.BOREDOM)==40)
__fresh();begin();__emit(nil,nil,{sourceKey='foreign-source'});R.advance('person',__body)
check('foreign_source_event_refused',outcome().status=='interrupted'and __stats:get(CharacterStat.BOREDOM)==40)
__fresh();begin();__emit(nil,nil,{actorId='foreign-actor'});R.advance('person',__body)
check('foreign_actor_event_refused',outcome().status=='interrupted'and __stats:get(CharacterStat.BOREDOM)==40)
__fresh();begin();__emit(nil,nil,{atHours=11});R.advance('person',__body)
check('future_content_timestamp_refused',outcome().status=='interrupted'and not __known['guid:line'])
__fresh();begin();__known['known']=true;__emit('BOR-1','known');R.advance('person',__body)
check('known_guid_no_source_replay',outcome().status=='completed'and __stats:get(CharacterStat.BOREDOM)==40)
__fresh();begin();__body.getMoodles=function()return {Update=function()error('controlled native Moodle callback failure')end}end
__emit('BOR-1','partial-line');R.advance('person',__body)
check('partial_source_failure_preserves_actual_effects',outcome().status=='interrupted'and __stats:get(CharacterStat.BOREDOM)==35
 and __known['partial-line']and outcome().after.BOREDOM==35 and outcome().nativeProgress.heardLines==0)
__fresh();__known['known']=true;__records=__roundtrip(__records);check('durable_state_roundtrip',__records.person.id=='person')
__fresh();begin();__tamper=true;__emit('CRP+2,RCP=Base.Make Butter Knife','xp-recipe');R.advance('person',__body)
check('durable_skill_tampering_refused',__requestAmount==100)
check('actual_source_xp_and_recipe',__xp.Woodwork==100 and __recipes['Base.Make Butter Knife']and __requests==1)
check('terminal_skill_request_retired',R.skillRequest('person',1,1)==nil)
__fresh();__level=10;begin();__emit('CRP+2,BOR-1','cutoff');R.advance('person',__body)
check('source_level_cutoff_preserves_other_effects',__requests==0 and __stats:get(CharacterStat.BOREDOM)==35)
__fresh();begin();__emit('BOR-1','cooldown:1');R.advance('person',__body)
check('source_cooldown_persisted',__records.person.leisureRadioCooldowns[2].BOR==30)
local retained=__records.person.leisureRadioCooldowns;R.onNativeTick();check('inactive_owned_source_actual_tick_cools',retained[2].BOR==29)
begin();R.onNativeTick();local once=retained[2].BOR;R.onNativeTick()
check('same_native_frame_no_double_cooldown',retained[2].BOR==once)
__emit('BOR-1','cooldown:2');R.advance('person',__body);check('new_guid_obeys_original_cooldown',__stats:get(CharacterStat.BOREDOM)==35 and __known['cooldown:2'])
__fresh();__on=false;begin();check('authentic_power_action_queued',#__queue==1 and __queue[1].mode=='ToggleOnOff'and not __on)
local powerAction=__queue[1];__runActions();check('authentic_power_action_native_result',__on and __buttons==1 and not outcome())
powerAction:perform();powerAction:complete();check('duplicate_source_action_does_not_toggle_again',__on and __buttons==1)
__emit();R.advance('person',__body);check('power_then_actual_hearing',outcome().status=='completed')
__fresh();begin('listen-native-radio',98000);check('native_channel_action_queued',#__queue==1 and __queue[1].mode=='SetChannel')
__runActions();__emit();R.advance('person',__body);check('native_channel_action_then_hearing',__channel==98000 and outcome().status=='completed')
__fresh();__on=false;begin();__delta=1;__queue[1]:perform()
check('premature_action_refused',not __on and outcome().status=='interrupted')
__fresh();__on=false;__queueRefusal=true;check('native_queue_refusal',not R.begin('person',__body,offer(),'purpose')and __registered==nil and not __on)
__fresh();local media={getID=function()return 2 end,getFullType=function()return 'Base.VHS_Retail' end,getMediaType=function()return 0 end,getMediaData=function()return __mediaData end}
__items[2]=media;begin('listen-native-media');check('original_media_and_play_actions_queued',#__queue==2 and __queue[1].deviceData==__data)
__runActions();check('native_media_insert_and_play_results',__inserted==1 and __mediaIndex==4 and __mediaPlaying and not outcome())
__emit('BOR-1','media-line');R.advance('person',__body);check('media_content_required_and_whole_media_not_claimed',outcome().status=='completed'and __mediaPlaying)
__fresh();__equipped=false;check('unprepared_radio_has_intent',#R.intentOffers('person',__body)==2 and #R.offers('person',__body)==0)
__fresh();begin();__items={};R.advance('person',__body);check('lost_custody_interrupts',outcome().status=='interrupted')
__fresh();begin();__equipped=false;R.advance('person',__body);check('lost_equipped_receiver_interrupts',outcome().status=='interrupted')
__fresh();begin();__power=0;R.advance('person',__body);check('native_power_loss_interrupts',outcome().status=='interrupted')
__fresh();begin();__channel=123;R.advance('person',__body);check('current_channel_mutation_interrupts',outcome().status=='interrupted')
__fresh();begin();__mediaIndex=88;R.advance('person',__body);check('current_media_mutation_interrupts',outcome().status=='interrupted')
__fresh();begin();__mediaPlaying=true;R.advance('person',__body);check('radio_to_media_mode_change_interrupts',outcome().status=='interrupted')
__fresh();begin();__records.person.leisureRadioWork.purposeId='forged-purpose';__emit();R.advance('person',__body)
check('durable_work_binding_tampering_refused',outcome().status=='interrupted'and outcome().purposeId=='purpose'and __stats:get(CharacterStat.BOREDOM)==40)
__fresh();begin();__records.person.leisureRadioWork.nativeProgress.heardLines=999;__emit();R.advance('person',__body)
check('durable_progress_cannot_forge_receipt',outcome().status=='completed'and outcome().nativeProgress.heardLines==1)
__fresh();__items[2]=media;begin('listen-native-media');__items={__radio};__delta=1;__queue[1]:start()
check('media_custody_revalidated_before_effect',outcome().status=='interrupted'and not __hasMedia and __inserted==0)
__fresh();__items={};__equipped=false;__objects={{key='object:radio',actorId='person',runtimeInstance='native-object'}}
__object={getObjectName=function()return 'Radio'end,getSpriteName=function()return 'appliances_radio_01_0'end,
 getDeviceData=function()return __data end,getSquare=function()return __square end}
local placed=offer();check('personally_acquired_native_placed_radio',placed and placed.sourceKind=='placed'and placed.objectKey=='object:radio')
begin();__tickCallback();__emit('BOR-1','placed-line',{x=10,y=10,z=0});R.advance('person',__body)
check('placed_native_line_original_square_check',outcome().status=='completed'and __stats:get(CharacterStat.BOREDOM)==35)
begin();__visible=false;__emit();R.advance('person',__body);check('placed_visibility_loss_interrupts',outcome().status=='interrupted')
__fresh();begin();__body:getModData().SAOExternalToken='generation:2';R.advance('person',__body);check('body_generation_change_interrupts',outcome().status=='interrupted')
__fresh();begin();check('foreign_interrupt_cannot_stop_work',not R.interrupt('person',{},'spoof')and R.work('person')~=nil)
__fresh();begin();__emit();__reload();check('reload_does_not_admit_retrospective_content',outcome().status=='interrupted'and __stats:get(CharacterStat.BOREDOM)==40 and __registered==nil)
check('no_operator_event_registration_from_original_source',__registrations==2)
local function battery(charge)
 local item={class='DrainableComboItem',getID=function()return 30 end,getFullType=function()return 'Base.Battery'end,
  getCurrentUsesFloat=function()return charge end,getMediaType=function()return -1 end,getMediaData=function()return nil end}
 __items[#__items+1]=item;return item
end
__fresh();__power=0;__data.canBePoweredHere=function()return true end
check('battery_power_capability_is_not_current_charge',#R.offers('person',__body)==0)
__fresh();__power=0;check('depleted_without_own_battery_no_offer',#R.offers('person',__body)==0)
battery(0);check('depleted_spare_no_power_promise',#R.offers('person',__body)==0)
__fresh();__power=0;__hasBattery=false;battery(.7);begin()
check('missing_battery_queues_native_insert',#__queue==1 and __queue[1].isRemove==false and __queue[1].deviceData==__data)
__runActions();check('original_battery_insertion_consumes_selected_spare',__hasBattery and __power==.7 and __batteryInserted==1 and #__items==1 and not outcome())
__emit();R.advance('person',__body)
check('battery_preparation_requires_actual_heard_content',outcome().status=='completed'and outcome().nativeProgress.nativeBatteryPreparation.inserted)
__fresh();__power=0;__on=false;battery(.6);begin()
check('depleted_battery_queues_remove_insert_power_order',#__queue==3 and __queue[1].isRemove==true and __queue[2].isRemove==false and __queue[3].mode=='ToggleOnOff')
__runActions();check('original_replacement_then_power_effect',__batteryRemoved==1 and __batteryInserted==1 and __power==.6 and __on and not outcome())
__fresh();__power=0;battery(.8);begin();__items={__radio};__queue[1]:start()
check('lost_selected_battery_refused_before_remove',outcome()and outcome().status=='interrupted'and __hasBattery and __batteryRemoved==0)
__fresh();__power=0;local selected=battery(.8);begin();selected.getCurrentUsesFloat=function()return .1 end;__queue[1]:start()
check('changed_selected_battery_charge_refused',outcome()and outcome().status=='interrupted'and __batteryRemoved==0)
__fresh();__power=0;battery(.8);begin();local removing=__queue[1];removing:start();__delta=1;removing:perform();removing:complete()
R.interrupt('person',__body,'urgent-survival')
check('partial_battery_preparation_remains_physical',not __hasBattery and __batteryRemoved==1 and __batteryInserted==0 and outcome().status=='interrupted'and outcome().nativeProgress.nativeBatteryPreparation.removed)
__fresh();__power=0;__hasBattery=false;battery(.8);begin();__data.addBattery=function()error('source battery hardware refused')end
__runActions();check('native_preparation_exception_retired',outcome().status=='interrupted'and not __hasBattery and __registered==nil and #__queue==0)
print('PASS D2 native radio '..count)
