local env = _G.NMCDPlayerWindowEnv
setfenv(1, env)

CDPLAYER_UI_SCALE = CDPLAYER_UI_SCALE or (500 / 350)
HEADER_SPAN_VERSION = HEADER_SPAN_VERSION or "cdplayer_header_500_v1"

local function scaled(value)
    return math.floor((tonumber(value) or 0) * CDPLAYER_UI_SCALE + 0.5)
end

local function S(value)
    if NMFancyDeviceUiScale and NMFancyDeviceUiScale.scaleValue then
        return NMFancyDeviceUiScale.scaleValue(value)
    end
    return math.floor((tonumber(value) or 0) + 0.5)
end

PANEL_W = PANEL_W or 500
PANEL_H = PANEL_H or 500
BG_X = BG_X or scaled(22)
BG_Y = BG_Y or scaled(10)
BG_W = BG_W or scaled(306)
BG_H = BG_H or scaled(330)
FRONT_X = FRONT_X or 34
FRONT_Y = FRONT_Y or 17
FRONT_W = FRONT_W or 432
FRONT_H = FRONT_H or 273
DISPLAY_X = DISPLAY_X or 167
DISPLAY_Y = DISPLAY_Y or 30
DISPLAY_W = DISPLAY_W or 166
DISPLAY_H = DISPLAY_H or 76
DISPLAY_VIEWPORT_INSET_X = DISPLAY_VIEWPORT_INSET_X or 14
DISPLAY_VIEWPORT_INSET_Y = DISPLAY_VIEWPORT_INSET_Y or 16
DISPLAY_VIEWPORT_W = DISPLAY_VIEWPORT_W or 138
DISPLAY_VIEWPORT_H = DISPLAY_VIEWPORT_H or 48
DISPLAY_TEXT_PAD_LEFT = DISPLAY_TEXT_PAD_LEFT or 4
DISPLAY_TEXT_PAD_RIGHT = DISPLAY_TEXT_PAD_RIGHT or 4
DISPLAY_TEXT_PAD_TOP = DISPLAY_TEXT_PAD_TOP or 4
DISPLAY_TEXT_PAD_BOTTOM = DISPLAY_TEXT_PAD_BOTTOM or 4
DISPLAY_TEXT_COLOR = DISPLAY_TEXT_COLOR or { r = 0x33 / 255, g = 0x44 / 255, b = 0x29 / 255, a = 1.0 }
DISPLAY_MODE_ICON_PAD_LEFT = DISPLAY_MODE_ICON_PAD_LEFT or 6
DISPLAY_MODE_ICON_PAD_TOP = DISPLAY_MODE_ICON_PAD_TOP or 4
DISPLAY_MODE_ICON_TARGET_W = DISPLAY_MODE_ICON_TARGET_W or 22
DISPLAY_MODE_ICON_TARGET_H = DISPLAY_MODE_ICON_TARGET_H or 17
DISPLAY_MODE_ICON_ALPHA = DISPLAY_MODE_ICON_ALPHA or 1.0
DISPLAY_BATTERY_W = DISPLAY_BATTERY_W or 22
DISPLAY_BATTERY_H = DISPLAY_BATTERY_H or 9
DISPLAY_BATTERY_PAD_TOP = DISPLAY_BATTERY_PAD_TOP or 8
DISPLAY_BATTERY_PAD_RIGHT = DISPLAY_BATTERY_PAD_RIGHT or 9
DISPLAY_BATTERY_FLASH_THRESHOLD = DISPLAY_BATTERY_FLASH_THRESHOLD or 0.05
DISPLAY_BATTERY_FLASH_INTERVAL_MS = DISPLAY_BATTERY_FLASH_INTERVAL_MS or 500
DISPLAY_CLOCK_PAD_TOP = DISPLAY_CLOCK_PAD_TOP or 4
DISPLAY_CLOCK_OFFSET_X = DISPLAY_CLOCK_OFFSET_X or -4
WORLD_CD_X = WORLD_CD_X or 76
WORLD_CD_Y = WORLD_CD_Y or 116
WORLD_CD_W = WORLD_CD_W or 349
WORLD_CD_H = WORLD_CD_H or 349
WORLD_CD_SPIN_DEG_PER_SEC = WORLD_CD_SPIN_DEG_PER_SEC or 1080
MODE_BUTTON_X = MODE_BUTTON_X or 77
MODE_BUTTON_Y = MODE_BUTTON_Y or 139
POWER_BUTTON_X = POWER_BUTTON_X or 401
POWER_BUTTON_Y = POWER_BUTTON_Y or 139
SIDE_BUTTON_W = SIDE_BUTTON_W or 24
SIDE_BUTTON_H = SIDE_BUTTON_H or 24
HOLD_BUTTON_X = HOLD_BUTTON_X or 363
HOLD_BUTTON_Y = HOLD_BUTTON_Y or 79
HOLD_BUTTON_W = HOLD_BUTTON_W or 27
HOLD_BUTTON_H = HOLD_BUTTON_H or 27
OPEN_BUTTON_X = OPEN_BUTTON_X or 36
OPEN_BUTTON_Y = OPEN_BUTTON_Y or 137
OPEN_BUTTON_W = OPEN_BUTTON_W or 28
OPEN_BUTTON_H = OPEN_BUTTON_H or 52
SETTINGS_GAP_Y = SETTINGS_GAP_Y or 22
MODE_LABEL_X = MODE_LABEL_X or 72
MODE_LABEL_Y = MODE_LABEL_Y or 163
MODE_LABEL_W = MODE_LABEL_W or 34
MODE_LABEL_H = MODE_LABEL_H or 12
HOLD_LABEL_X = HOLD_LABEL_X or 363
HOLD_LABEL_Y = HOLD_LABEL_Y or 70
HOLD_LABEL_W = HOLD_LABEL_W or 27
HOLD_LABEL_H = HOLD_LABEL_H or 10
POWER_LABEL_X = POWER_LABEL_X or 395
POWER_LABEL_Y = POWER_LABEL_Y or 163
POWER_LABEL_W = POWER_LABEL_W or 35
POWER_LABEL_H = POWER_LABEL_H or 12
POWER_INDICATOR_X = POWER_INDICATOR_X or (HOLD_BUTTON_X + HOLD_BUTTON_W)
POWER_INDICATOR_Y = POWER_INDICATOR_Y or (HOLD_BUTTON_Y + HOLD_BUTTON_H)
POWER_INDICATOR_W = POWER_INDICATOR_W or 10
POWER_INDICATOR_H = POWER_INDICATOR_H or 10
BUTTON_CLUSTER_X = BUTTON_CLUSTER_X or 95
BUTTON_CLUSTER_Y = BUTTON_CLUSTER_Y or 54
BUTTON_CLUSTER_W = BUTTON_CLUSTER_W or 64
BUTTON_CLUSTER_H = BUTTON_CLUSTER_H or 64
BUTTON_CENTER_RENDER_X = BUTTON_CENTER_RENDER_X or 18
BUTTON_CENTER_RENDER_Y = BUTTON_CENTER_RENDER_Y or 18
BUTTON_CENTER_RENDER_W = BUTTON_CENTER_RENDER_W or 28
BUTTON_CENTER_RENDER_H = BUTTON_CENTER_RENDER_H or 28
BUTTON_LEFT_RENDER_X = BUTTON_LEFT_RENDER_X or 0
BUTTON_LEFT_RENDER_Y = BUTTON_LEFT_RENDER_Y or 11
BUTTON_LEFT_RENDER_W = BUTTON_LEFT_RENDER_W or 19
BUTTON_LEFT_RENDER_H = BUTTON_LEFT_RENDER_H or 42
BUTTON_TOP_RENDER_X = BUTTON_TOP_RENDER_X or 11
BUTTON_TOP_RENDER_Y = BUTTON_TOP_RENDER_Y or 0
BUTTON_TOP_RENDER_W = BUTTON_TOP_RENDER_W or 42
BUTTON_TOP_RENDER_H = BUTTON_TOP_RENDER_H or 19
BUTTON_RIGHT_RENDER_X = BUTTON_RIGHT_RENDER_X or 45
BUTTON_RIGHT_RENDER_Y = BUTTON_RIGHT_RENDER_Y or 11
BUTTON_RIGHT_RENDER_W = BUTTON_RIGHT_RENDER_W or 19
BUTTON_RIGHT_RENDER_H = BUTTON_RIGHT_RENDER_H or 42
BUTTON_BOTTOM_RENDER_X = BUTTON_BOTTOM_RENDER_X or 11
BUTTON_BOTTOM_RENDER_Y = BUTTON_BOTTOM_RENDER_Y or 45
BUTTON_BOTTOM_RENDER_W = BUTTON_BOTTOM_RENDER_W or 42
BUTTON_BOTTOM_RENDER_H = BUTTON_BOTTOM_RENDER_H or 19
BUTTON_CENTER_HIT_INSET_X = BUTTON_CENTER_HIT_INSET_X or 2
BUTTON_CENTER_HIT_INSET_Y = BUTTON_CENTER_HIT_INSET_Y or 2
BUTTON_CENTER_HIT_W = BUTTON_CENTER_HIT_W or 24
BUTTON_CENTER_HIT_H = BUTTON_CENTER_HIT_H or 24
BUTTON_SIDE_HIT_INSET_AXIS = BUTTON_SIDE_HIT_INSET_AXIS or 1
BUTTON_SIDE_HIT_W = BUTTON_SIDE_HIT_W or 16
BUTTON_SIDE_HIT_H = BUTTON_SIDE_HIT_H or 24
BUTTON_VERT_HIT_INSET_AXIS = BUTTON_VERT_HIT_INSET_AXIS or 1
BUTTON_VERT_HIT_W = BUTTON_VERT_HIT_W or 24
BUTTON_VERT_HIT_H = BUTTON_VERT_HIT_H or 16
BUTTON_PRESS_OFFSET_PX = BUTTON_PRESS_OFFSET_PX or 1
BUTTON_PRESS_LINGER_MS = BUTTON_PRESS_LINGER_MS or 90
BUTTON_VOLUME_STEP_PCT = BUTTON_VOLUME_STEP_PCT or 5
BUTTON_PRESSED_TINT_R = BUTTON_PRESSED_TINT_R or 0.72
BUTTON_PRESSED_TINT_G = BUTTON_PRESSED_TINT_G or 0.72
BUTTON_PRESSED_TINT_B = BUTTON_PRESSED_TINT_B or 0.72
OPEN_BUTTON_PRESS_OFFSET_X = OPEN_BUTTON_PRESS_OFFSET_X or 2
SIDE_BUTTON_PRESSED_INSET_PX = SIDE_BUTTON_PRESSED_INSET_PX or 1
HOLD_BUTTON_ANGLE_UPRIGHT = HOLD_BUTTON_ANGLE_UPRIGHT or 0.0
HOLD_BUTTON_ANGLE_HELD = HOLD_BUTTON_ANGLE_HELD or 135.0
HOLD_BUTTON_ANIMATION_DURATION_MS = HOLD_BUTTON_ANIMATION_DURATION_MS or 280
SLOT_SIZE = SLOT_SIZE or 40
SLOT_AREA_X = SLOT_AREA_X or 151
SLOT_AREA_Y = SLOT_AREA_Y or 397
SLOT_AREA_W = SLOT_AREA_W or 198
SLOT_AREA_H = SLOT_AREA_H or 84
HEADPHONE_SLOT_X = HEADPHONE_SLOT_X or (SLOT_AREA_X + 15)
HEADPHONE_SLOT_Y = HEADPHONE_SLOT_Y or (SLOT_AREA_Y + 15)
MEDIA_SLOT_X = MEDIA_SLOT_X or (SLOT_AREA_X + 79)
MEDIA_SLOT_Y = MEDIA_SLOT_Y or (SLOT_AREA_Y + 25)
BATTERY_SLOT_X = BATTERY_SLOT_X or (SLOT_AREA_X + SLOT_AREA_W - 15 - SLOT_SIZE)
BATTERY_SLOT_Y = BATTERY_SLOT_Y or (SLOT_AREA_Y + 15)
BATTERY_METER_X = BATTERY_METER_X or BATTERY_SLOT_X
BATTERY_METER_Y = BATTERY_METER_Y or (BATTERY_SLOT_Y + SLOT_SIZE + 4)
BATTERY_METER_W = BATTERY_METER_W or SLOT_SIZE
BATTERY_METER_H = BATTERY_METER_H or 4
BATTERY_METER_BG = BATTERY_METER_BG or { a = 0.95, r = 0.05, g = 0.05, b = 0.05 }
BATTERY_METER_FILL = BATTERY_METER_FILL or { a = 0.95, r = 0.20, g = 0.80, b = 0.20 }
BATTERY_METER_EMPTY = BATTERY_METER_EMPTY or { a = 0.95, r = 0.80, g = 0.14, b = 0.14 }
DEFAULT_RIGHT_MARGIN = DEFAULT_RIGHT_MARGIN or 24
EXPANDED_BOTTOM_MARGIN = EXPANDED_BOTTOM_MARGIN or 0
EXPANDED_BOTTOM_OVERSHOOT = EXPANDED_BOTTOM_OVERSHOOT or 18
COLLAPSED_HIDDEN_FROM_BOTTOM = COLLAPSED_HIDDEN_FROM_BOTTOM or 370
DRAG_THRESHOLD_X = DRAG_THRESHOLD_X or 6
ANIMATION_DURATION_MS = ANIMATION_DURATION_MS or 300
CLOSE_X = CLOSE_X or 75
CLOSE_Y = CLOSE_Y or 114
CLOSE_W = CLOSE_W or scaled(10)
CLOSE_H = CLOSE_H or scaled(10)
CLOSE_TEXTURE_ALPHA = CLOSE_TEXTURE_ALPHA or 0.5
CLOSE_TEXTURE_TINT_R = CLOSE_TEXTURE_TINT_R or 0.0
CLOSE_TEXTURE_TINT_G = CLOSE_TEXTURE_TINT_G or 0.0
CLOSE_TEXTURE_TINT_B = CLOSE_TEXTURE_TINT_B or 0.0
PERSISTED_UI_STATE_KEY = PERSISTED_UI_STATE_KEY or "NMCDPlayerUIState"
RESTORE_RETRY_WINDOW_MS = RESTORE_RETRY_WINDOW_MS or 8000
BASE_TEXTURE_PATH = BASE_TEXTURE_PATH or "media/textures/UI/CDPlayer/NM_UI_CDPlayer_Base.png"
FRONT_TEXTURE_PATH_PREFIX = FRONT_TEXTURE_PATH_PREFIX or "media/textures/UI/CDPlayer/NM_UI_CDPlayer_Front_"
FRONT_TEXTURE_FALLBACK_VARIANT = FRONT_TEXTURE_FALLBACK_VARIANT or "Cyan"
LID_TEXTURE_PATH_PREFIX = LID_TEXTURE_PATH_PREFIX or "media/textures/UI/CDPlayer/NM_UI_CDPlayer_Lid_"
DISPLAY_TEXTURE_PATH = DISPLAY_TEXTURE_PATH or "media/textures/UI/CDPlayer/NM_UI_CDPlayer_Display.png"
DISPLAY_TEXTURE_ON_PATH = DISPLAY_TEXTURE_ON_PATH or "media/textures/UI/CDPlayer/NM_UI_CDPlayer_Display_On.png"
AUX_INGRESS_TEXTURE_PATH = AUX_INGRESS_TEXTURE_PATH or "media/textures/UI/CDPlayer/NM_UI_CDPlayer_AuxIngress.png"
SIDE_BUTTON_TEXTURE_PATH = SIDE_BUTTON_TEXTURE_PATH or "media/textures/UI/CDPlayer/NM_UI_CDPlayer_Button_Power.png"
SIDE_BUTTON_BG_TEXTURE_PATH = SIDE_BUTTON_BG_TEXTURE_PATH or "media/textures/UI/CDPlayer/NM_UI_CDPlayer_Button_Power_BG.png"
POWER_INDICATOR_TEXTURE_ON_PATH = POWER_INDICATOR_TEXTURE_ON_PATH or "media/textures/UI/CDPlayer/NM_UI_CDPlayer_Indicator_Power_On.png"
POWER_INDICATOR_TEXTURE_OFF_PATH = POWER_INDICATOR_TEXTURE_OFF_PATH or "media/textures/UI/CDPlayer/NM_UI_CDPlayer_Indicator_Power_Off.png"
POWER_INDICATOR_TEXTURE_STANDBY_PATH = POWER_INDICATOR_TEXTURE_STANDBY_PATH or "media/textures/UI/CDPlayer/NM_UI_CDPlayer_Indicator_Power_Standby.png"
HOLD_BUTTON_TEXTURE_PATH = HOLD_BUTTON_TEXTURE_PATH or "media/textures/UI/CDPlayer/NM_UI_CDPlayer_Button_Hold.png"
OPEN_BUTTON_TEXTURE_PATH = OPEN_BUTTON_TEXTURE_PATH or "media/textures/UI/CDPlayer/NM_UI_CDPlayer_Button_Open.png"
MODE_LABEL_TEXTURE_PATH = MODE_LABEL_TEXTURE_PATH or "media/textures/UI/CDPlayer/NM_UI_CDPlayer_Label_Mode.png"
HOLD_LABEL_TEXTURE_PATH = HOLD_LABEL_TEXTURE_PATH or "media/textures/UI/CDPlayer/NM_UI_CDPlayer_Label_Hold.png"
POWER_LABEL_TEXTURE_PATH = POWER_LABEL_TEXTURE_PATH or "media/textures/UI/CDPlayer/NM_UI_CDPlayer_Label_Power.png"
DISPLAY_MODE_ICON_AUTOPLAY_TEXTURE_PATH = DISPLAY_MODE_ICON_AUTOPLAY_TEXTURE_PATH or "media/textures/UI/CDPlayer/NM_UI_CDPlayer_Display_Mode_Autoplay.png"
DISPLAY_MODE_ICON_LOOP_SONG_TEXTURE_PATH = DISPLAY_MODE_ICON_LOOP_SONG_TEXTURE_PATH or "media/textures/UI/CDPlayer/NM_UI_CDPlayer_Display_Mode_LoopSong.png"
DISPLAY_MODE_ICON_LOOP_ALBUM_TEXTURE_PATH = DISPLAY_MODE_ICON_LOOP_ALBUM_TEXTURE_PATH or "media/textures/UI/CDPlayer/NM_UI_CDPlayer_Display_Mode_LoopAlbum.png"
DISPLAY_MODE_ICON_SHUFFLE_TEXTURE_PATH = DISPLAY_MODE_ICON_SHUFFLE_TEXTURE_PATH or "media/textures/UI/CDPlayer/NM_UI_CDPlayer_Display_Mode_Shuffle.png"
BUTTON_TEXTURE_PREV_PATH = BUTTON_TEXTURE_PREV_PATH or "media/textures/UI/CDPlayer/NM_UI_CDPlayer_Button_Prev.png"
BUTTON_TEXTURE_NEXT_PATH = BUTTON_TEXTURE_NEXT_PATH or "media/textures/UI/CDPlayer/NM_UI_CDPlayer_Button_Next.png"
BUTTON_TEXTURE_VOL_UP_PATH = BUTTON_TEXTURE_VOL_UP_PATH or "media/textures/UI/CDPlayer/NM_UI_CDPlayer_Button_Vol_Up.png"
BUTTON_TEXTURE_VOL_DOWN_PATH = BUTTON_TEXTURE_VOL_DOWN_PATH or "media/textures/UI/CDPlayer/NM_UI_CDPlayer_Button_Vol_Down.png"
BUTTON_TEXTURE_PLAY_STOP_PATH = BUTTON_TEXTURE_PLAY_STOP_PATH or "media/textures/UI/CDPlayer/NM_UI_CDPlayer_Button_Play_Stop.png"
CLOSE_TEXTURE_PATH = CLOSE_TEXTURE_PATH or "media/textures/UI/Walkman/NM_UI_Walkman_Close.png"
HEADER_ROW_TOP = HEADER_ROW_TOP or scaled(10)
HEADER_ROW_BOTTOM = HEADER_ROW_BOTTOM or scaled(267)
HEADER_OUTER_CENTER_X = HEADER_OUTER_CENTER_X or scaled(175)
HEADER_OUTER_CENTER_Y = HEADER_OUTER_CENTER_Y or scaled(267)
HEADER_OUTER_RADIUS_X = HEADER_OUTER_RADIUS_X or scaled(153)
HEADER_OUTER_RADIUS_Y = HEADER_OUTER_RADIUS_Y or scaled(257)
HEADER_INNER_TOP = HEADER_INNER_TOP or scaled(120)
HEADER_INNER_CENTER_X = HEADER_INNER_CENTER_X or scaled(175)
HEADER_INNER_CENTER_Y = HEADER_INNER_CENTER_Y or scaled(281)
HEADER_INNER_RADIUS_X = HEADER_INNER_RADIUS_X or scaled(103)
HEADER_INNER_RADIUS_Y = HEADER_INNER_RADIUS_Y or scaled(161)
HEADER_INNER_LEG_BOTTOM = HEADER_INNER_LEG_BOTTOM or HEADER_ROW_BOTTOM
HEADER_INNER_MIN_HALF_WIDTH = HEADER_INNER_MIN_HALF_WIDTH or scaled(70)
HEADER_OUTER_MIN_HALF_WIDTH = HEADER_OUTER_MIN_HALF_WIDTH or scaled(128)
HEADER_ROW_SPANS = HEADER_ROW_SPANS or {}
LID_CLOSED_X = LID_CLOSED_X or 34
LID_CLOSED_Y = LID_CLOSED_Y or 109
LID_W = LID_W or 432
LID_CLOSED_H = LID_CLOSED_H or 372
LID_OPEN_H = LID_OPEN_H or 191
LID_OPEN_Y = LID_OPEN_Y or (LID_CLOSED_Y + LID_CLOSED_H - LID_OPEN_H)
LID_ANIMATION_DURATION_MS = LID_ANIMATION_DURATION_MS or 420
LID_OPEN_ZONE_H = LID_OPEN_ZONE_H or 181

CDPLAYER_LAYOUT_KEYS = CDPLAYER_LAYOUT_KEYS or {
    "PANEL_W", "PANEL_H", "BG_X", "BG_Y", "BG_W", "BG_H", "FRONT_X", "FRONT_Y", "FRONT_W", "FRONT_H",
    "DISPLAY_X", "DISPLAY_Y", "DISPLAY_W", "DISPLAY_H", "DISPLAY_VIEWPORT_INSET_X", "DISPLAY_VIEWPORT_INSET_Y", "DISPLAY_VIEWPORT_W", "DISPLAY_VIEWPORT_H",
    "DISPLAY_TEXT_PAD_LEFT", "DISPLAY_TEXT_PAD_RIGHT", "DISPLAY_TEXT_PAD_TOP", "DISPLAY_TEXT_PAD_BOTTOM", "DISPLAY_MODE_ICON_PAD_LEFT", "DISPLAY_MODE_ICON_PAD_TOP",
    "DISPLAY_MODE_ICON_TARGET_W", "DISPLAY_MODE_ICON_TARGET_H", "DISPLAY_BATTERY_W", "DISPLAY_BATTERY_H", "DISPLAY_BATTERY_PAD_TOP", "DISPLAY_BATTERY_PAD_RIGHT",
    "DISPLAY_CLOCK_PAD_TOP", "DISPLAY_CLOCK_OFFSET_X", "WORLD_CD_X", "WORLD_CD_Y", "WORLD_CD_W", "WORLD_CD_H", "MODE_BUTTON_X", "MODE_BUTTON_Y", "POWER_BUTTON_X", "POWER_BUTTON_Y",
    "SIDE_BUTTON_W", "SIDE_BUTTON_H", "HOLD_BUTTON_X", "HOLD_BUTTON_Y", "HOLD_BUTTON_W", "HOLD_BUTTON_H", "OPEN_BUTTON_X", "OPEN_BUTTON_Y", "OPEN_BUTTON_W", "OPEN_BUTTON_H", "SETTINGS_GAP_Y",
    "MODE_LABEL_X", "MODE_LABEL_Y", "MODE_LABEL_W", "MODE_LABEL_H", "HOLD_LABEL_X", "HOLD_LABEL_Y", "HOLD_LABEL_W", "HOLD_LABEL_H", "POWER_LABEL_X", "POWER_LABEL_Y", "POWER_LABEL_W", "POWER_LABEL_H",
    "POWER_INDICATOR_X", "POWER_INDICATOR_Y", "POWER_INDICATOR_W", "POWER_INDICATOR_H", "BUTTON_CLUSTER_X", "BUTTON_CLUSTER_Y", "BUTTON_CLUSTER_W", "BUTTON_CLUSTER_H",
    "BUTTON_CENTER_RENDER_X", "BUTTON_CENTER_RENDER_Y", "BUTTON_CENTER_RENDER_W", "BUTTON_CENTER_RENDER_H", "BUTTON_LEFT_RENDER_X", "BUTTON_LEFT_RENDER_Y", "BUTTON_LEFT_RENDER_W", "BUTTON_LEFT_RENDER_H",
    "BUTTON_TOP_RENDER_X", "BUTTON_TOP_RENDER_Y", "BUTTON_TOP_RENDER_W", "BUTTON_TOP_RENDER_H", "BUTTON_RIGHT_RENDER_X", "BUTTON_RIGHT_RENDER_Y", "BUTTON_RIGHT_RENDER_W", "BUTTON_RIGHT_RENDER_H",
    "BUTTON_BOTTOM_RENDER_X", "BUTTON_BOTTOM_RENDER_Y", "BUTTON_BOTTOM_RENDER_W", "BUTTON_BOTTOM_RENDER_H", "BUTTON_CENTER_HIT_INSET_X", "BUTTON_CENTER_HIT_INSET_Y", "BUTTON_CENTER_HIT_W", "BUTTON_CENTER_HIT_H",
    "BUTTON_SIDE_HIT_INSET_AXIS", "BUTTON_SIDE_HIT_W", "BUTTON_SIDE_HIT_H", "BUTTON_VERT_HIT_INSET_AXIS", "BUTTON_VERT_HIT_W", "BUTTON_VERT_HIT_H", "BUTTON_PRESS_OFFSET_PX",
    "OPEN_BUTTON_PRESS_OFFSET_X", "SIDE_BUTTON_PRESSED_INSET_PX", "SLOT_SIZE", "SLOT_AREA_X", "SLOT_AREA_Y", "SLOT_AREA_W", "SLOT_AREA_H",
    "HEADPHONE_SLOT_X", "HEADPHONE_SLOT_Y", "MEDIA_SLOT_X", "MEDIA_SLOT_Y", "BATTERY_SLOT_X", "BATTERY_SLOT_Y", "BATTERY_METER_X", "BATTERY_METER_Y", "BATTERY_METER_W", "BATTERY_METER_H",
    "DEFAULT_RIGHT_MARGIN", "EXPANDED_BOTTOM_MARGIN", "EXPANDED_BOTTOM_OVERSHOOT", "COLLAPSED_HIDDEN_FROM_BOTTOM", "DRAG_THRESHOLD_X", "CLOSE_X", "CLOSE_Y", "CLOSE_W", "CLOSE_H",
    "HEADER_ROW_TOP", "HEADER_ROW_BOTTOM", "HEADER_OUTER_CENTER_X", "HEADER_OUTER_CENTER_Y", "HEADER_OUTER_RADIUS_X", "HEADER_OUTER_RADIUS_Y",
    "HEADER_INNER_TOP", "HEADER_INNER_CENTER_X", "HEADER_INNER_CENTER_Y", "HEADER_INNER_RADIUS_X", "HEADER_INNER_RADIUS_Y", "HEADER_INNER_LEG_BOTTOM", "HEADER_INNER_MIN_HALF_WIDTH", "HEADER_OUTER_MIN_HALF_WIDTH",
    "LID_CLOSED_X", "LID_CLOSED_Y", "LID_W", "LID_CLOSED_H", "LID_OPEN_H", "LID_OPEN_Y", "LID_OPEN_ZONE_H"
}

CDPLAYER_LAYOUT_BASE = CDPLAYER_LAYOUT_BASE or {}
for i = 1, #CDPLAYER_LAYOUT_KEYS do
    local key = CDPLAYER_LAYOUT_KEYS[i]
    if CDPLAYER_LAYOUT_BASE[key] == nil then
        CDPLAYER_LAYOUT_BASE[key] = env[key]
    end
end

function refreshCDPlayerLayoutMetrics()
    for i = 1, #CDPLAYER_LAYOUT_KEYS do
        local key = CDPLAYER_LAYOUT_KEYS[i]
        local base = CDPLAYER_LAYOUT_BASE[key]
        if base ~= nil then
            env[key] = S(base)
        end
    end
end

refreshCDPlayerLayoutMetrics()
