---AUTOMATICALLY GENERATED FROM Script/formatTimedActionBlocker.py
---
---Holds the data of the timed actions to allow while mounted on a horse.
local ActionBlocker = {
    ---Valid timed actions while horse riding.
    ---@type table<string, true>
    validActions = {
        ["HealthPanelAction"] = true,
        ["HorseMod_DismountAction"] = true,
        ["HorseMod_HorseJump"] = true,
        ["HorseMod_UrgentDismountAction"] = true,
        ["ISAddFluidFromItemAction"] = true,
        ["ISApplyBandage"] = true,
        ["ISApplyMakeUp"] = true,
        ["ISAttachItemHotbar"] = true,
        ["ISCleanBandage"] = true,
        ["ISClothingExtraAction"] = true,
        ["ISCutHair"] = true,
        ["ISDetachItemHotbar"] = true,
        ["ISDisinfect"] = true,
        ["ISDrinkFluidAction"] = true,
        ["ISDrinkFromBottle"] = true,
        ["ISDropCorpseAction"] = true,
        ["ISDropWorldItemAction"] = true,
        ["ISDryMyself"] = true,
        ["ISDyeHair"] = true,
        ["ISEatFoodAction"] = true,
        ["ISEjectMagazine"] = true,
        ["ISFeedAnimalFromHand"] = true,
        ["ISFluidEmptyAction"] = true,
        ["ISFluidPanelAction"] = true,
        ["ISFluidTransferAction"] = true,
        ["ISGrabItemAction"] = true,
        ["ISHurricaneLanternExtinguish"] = true,
        ["ISInsertLightSourceFuelAction"] = true,
        ["ISInsertMagazine"] = true,
        ["ISInventoryTransferAction"] = true,
        ["ISItemSlotAddAction"] = true,
        ["ISItemSlotRemoveAction"] = true,
        ["ISKillAnimalInInventory"] = true,
        ["ISLoadBulletsInMagazine"] = true,
        ["ISMedicalCheckAction"] = true,
        ["ISOpenAnimalInfo"] = true,
        ["ISPetAnimal"] = true,
        ["ISRackFirearm"] = true,
        ["ISRadioAction"] = true,
        ["ISReadABook"] = true,
        ["ISReadWorldMap"] = true,
        ["ISReloadWeaponAction"] = true,
        ["ISRemoveBullet"] = true,
        ["ISRemoveGlass"] = true,
        ["ISRemoveLightSourceFuelAction"] = true,
        ["ISRemovePatch"] = true,
        ["ISRepairClothing"] = true,
        ["ISStitch"] = true,
        ["ISTakePillAction"] = true,
        ["ISTransferWaterAction"] = true,
        ["ISTrimBeard"] = true,
        ["ISUnequipAction"] = true,
        ["ISUnloadBulletsFromFirearm"] = true,
        ["ISUnloadBulletsFromMagazine"] = true,
        ["ISWalkToTimedAction"] = true,
        ["ISWalkToTimedActionF"] = true,
        ["ISWearClothing"] = true,
        ["ISWriteSomething"] = true,
    },
}

return ActionBlocker