--------------------------------------------------------------------------------------------------
--		----	  |			  |			|		 |				|    --    |      ----			--
--		----	  |			  |			|		 |				|    --	   |      ----			--
--		----	  |		-------	   -----|	 ---------		-----          -      ----	   -------
--		----	  |			---			|		 -----		------        --      ----			--
--		----	  |			---			|		 -----		-------	 	 ---      ----			--
--		----	  |		-------	   ----------	 -----		-------		 ---      ----	   -------
--			|	  |		-------			|		 -----		-------		 ---		  |			--
--			|	  |		-------			|	 	 -----		-------		 ---		  |			--
--------------------------------------------------------------------------------------------------

InventionsMenu = InventionsMenu or {}
InventionsMenu.workbench = InventionsMenu.workbench or {}

local actionTime = { -- 600 ticks ~1min
	epic = 40000, -- +1 hours
	verylong = 26000, -- ~45 mins
	long = 18000, -- ~30 mins
	midlong = 15000, -- ~25 mins
	mid = 10000, -- ~15 mins
	midshort = 6000, -- ~10 min
	short = 3000, -- ~5 min / ~3 min
	shortest = 1250, -- ~2.5 min / ~1.5 min
}

local costTable = {
	-- CURIOS
	curioVerySimple = {
		["Base.ScrapMetal"]=1,
		["Base.ElectronicsScrap"]=1,
	},
	curioSimple = {
		["Base.ScrapMetal"]=3,
		["Base.ElectronicsScrap"]=2,
		["Base.Screws"]=4,
	},
	curio = {
		["Base.ScrapMetal"]=6,
		["Base.ElectronicsScrap"]=4,
		["Base.Screws"]=8,
		["Base.Wire"]=2,
	},
	curioComplex = {
		["Base.ScrapMetal"]=12,
		["Base.ElectronicsScrap"]=7,
		["Base.Screws"]=16,
		["Base.Wire"]=4,
		["Base.ElectricWire"]=2,
	},
	curioVeryComplex = {
		["Base.ScrapMetal"]=20,
		["Base.ElectronicsScrap"]=10,
		["Base.Screws"]=30,
		["Base.TriggerCrafted"]=1,
	},
	-- SCRAP
	scrapVerySimple = {
		["Base.ScrapMetal"]=2,
	},
	scrapSimple = {
		["Base.ScrapMetal"]=3,
		["Base.MetalPipe"]=1,
	},
	scrap = {
		["Base.ScrapMetal"]=6,
		["Base.MetalPipe"]=2,
	},
	scrapComplex = {
		["Base.ScrapMetal"]=10,
		["Base.MetalPipe"]=3,
		["Base.MetalBar"]=2,
		["Base.Screws"]=8,
	},
	scrapVeryComplex = {
		["Base.ScrapMetal"]=16,
		["Base.MetalPipe"]=4,
		["Base.MetalBar"]=3,
		["Base.SmallSheetMetal"]=2,
		["Base.Screws"]=16,
		["Base.NutsBolts"]=8,
	},
	-- WOODEN
	woodVerySimple = {
		["Base.Plank"]=1,
	},
	woodSimple = {
		["Base.Plank"]=2,
		["Base.Woodglue"]=1,
	},
	wood = {
		["Base.Plank"]=4,
		["Base.Nails"]=6,
		["Base.Woodglue"]=1,
	},
	woodComplex = {
		["Base.Plank"]=8,
		["Base.Nails"]=12,
		["Base.Woodglue"]=2,
		["Base.Screws"]=4,
	},

	woodVeryComplex = {
		["Base.Plank"]=14,
		["Base.Nails"]=24,
		["Base.Woodglue"]=3,
		["Base.Screws"]=10,
		["Base.Hinge"]=2,
	},
	-- CLOTH
	clothVerySimple = {
		["Base.RippedSheets"]=1,
		["Base.Thread"]=1,
	},
	clothSimple = {
		["Base.RippedSheets"]=2,
		["Base.Thread"]=1,
	},
	cloth = {
		["Base.RippedSheets"]=4,
		["Base.Thread"]=2,
	},
	clothComplex = {
		["Base.RippedSheets"]=6,
		["Base.Thread"]=3,
		["Base.DenimStrips"]=2,
	},
	clothVeryComplex = {
		["Base.RippedSheets"]=10,
		["Base.Thread"]=5,
		["Base.DenimStrips"]=4,
		["Base.LeatherStrips"]=2,
	},
	-- COSTUMES
	costumeVerySimple = {
		["Base.RippedSheets"]=3,
		["Base.Thread"]=2,
	},
	costumeSimple = {
		["Base.RippedSheets"]=5,
		["Base.Thread"]=3,
		["Base.DenimStrips"]=1,
	},
	costume = {
		["Base.RippedSheets"]=8,
		["Base.Thread"]=5,
		["Base.DenimStrips"]=3,
	},
	costumeComplex = {
		["Base.RippedSheets"]=12,
		["Base.Thread"]=8,
		["Base.DenimStrips"]=5,
		["Base.LeatherStrips"]=3,
	},
	costumeVeryComplex = {
		["Base.RippedSheets"]=18,
		["Base.Thread"]=12,
		["Base.DenimStrips"]=8,
		["Base.LeatherStrips"]=6,
		["Base.Button"]=6,
	},
}

InventionsMenu.workbench.toysLib = {
	-- level 10 -- 1
	{level=10,invType="obj",invName="WaterPump",invResult="camping_01_64",baseDuration=actionTime.epic,group="Curios",
		cost=costTable.scrapVeryComplex,
	},
	-- level 9 -- 1
	{level=9,invType="item",invName="WoodToyShip",invResult="Lifestyle.WoodToyShip",baseDuration=actionTime.long,group="Toys",
		cost=costTable.woodVeryComplex,
	},
	{level=9,invType="item",invName="DemonCore",invResult="Lifestyle.DemonCore",baseDuration=actionTime.long,group="Curios",
		cost=costTable.curioComplex,
	},
	-- level 8 -- 4
	{level=8,invType="item",invName="Rifle_CapGun",invResult="Base.Rifle_CapGun",baseDuration=actionTime.long,group="Toys",
		cost=costTable.scrapComplex,
	},
	{level=8,invType="item",invName="EyeOfCthulhu",invResult="Base.EyeOfCthulhu",baseDuration=actionTime.long,group="Toys",
		cost=costTable.clothComplex,
	},
	{level=8,invType="item",invName="SpiffoSuit",invResult="Base.SpiffoSuit",baseDuration=actionTime.long,group="Costumes",
		cost=costTable.costumeComplex,
	},
	{level=8,invType="item",invName="ScrapBushSeed",invResult="Lifestyle.ScrapBushSeed",baseDuration=actionTime.long,group="Curios",
		cost={
			["Base.ScrapMetal"]=12,
			["Base.Fertilizer"]=4,
			["Base.RubberBand"]=3,
			["Base.Glue"]=4,
			["Base.GunPowder"]=2,
			["Base.NutsBolts"]=1,
		},
	},
	-- level 7 -- 5
	{level=7,invType="item",invName="PotScrubberFrog",invResult="Base.PotScrubberFrog",baseDuration=actionTime.midlong,group="Toys",
		cost=costTable.scrap,
	},
	{level=7,invType="item",invName="TrashGoblin",invResult="Base.TrashGoblin",baseDuration=actionTime.midlong,group="Toys",
		cost=costTable.cloth,
	},
	{level=7,invType="item",invName="Pocketwatch",invResult="Base.Pocketwatch",baseDuration=actionTime.midlong,group="Costumes",
		cost=costTable.scrap,
	},
	{level=7,invType="item",invName="Hat_Spiffo",invResult="Base.Hat_Spiffo",baseDuration=actionTime.midlong,group="Costumes",
		cost=costTable.costumeComplex,
	},
	{level=7,invType="obj",invName="Gramophone",invResult="LS_Inventions_2",baseDuration=actionTime.verylong,group="Curios",
		cost={
			["Base.ScrapMetal"]=20,
			["Base.ElectronicsScrap"]=10,
			["Base.BrassScrap"]=10,
			["Base.Screws"]=20,
			["Base.Amplifier"]=2,
			["Base.ElectricWire"]=3,
			["Base.Speaker"]=1,
			["Base.CDplayer"]=1,
			["Base.Plank"]=1,
		},
	},
	-- level 6 -- 6
	{level=6,invType="item",invName="MetalToyRobot",invResult="Lifestyle.MetalToyRobot",baseDuration=actionTime.midlong,group="Toys",
		cost=costTable.scrapComplex,
	},
	{level=6,invType="item",invName="SnowGlobe",invResult="Base.SnowGlobe",baseDuration=actionTime.mid,group="Toys",
		cost=costTable.scrap,
	},
	{level=6,invType="item",invName="SpiffoTail",invResult="Base.SpiffoTail",baseDuration=actionTime.mid,group="Costumes",
		cost=costTable.cloth,
	},
	{level=6,invType="item",invName="Hat_Pirate",invResult="Base.Hat_Pirate",baseDuration=actionTime.mid,group="Costumes",
		cost=costTable.costume,
	},
	{level=6,invType="item",invName="SheepElectricShears",invResult="Base.SheepElectricShears",baseDuration=actionTime.midlong,group="Curios",
		cost=costTable.curio,
	},
	{level=6,invType="item",invName="Bullhorn",invResult="Base.Bullhorn",baseDuration=actionTime.long,group="Curios",
		cost={
			["Base.ScrapMetal"]=12,
			["Base.ElectronicsScrap"]=2,
			["Base.Screws"]=6,
			["Base.Amplifier"]=1,
			["Base.ElectricWire"]=1,
		},
	},
	-- level 5 - 8
	{level=5,invType="item",invName="Revolver_CapGun",invResult="Base.Revolver_CapGun",baseDuration=actionTime.mid,group="Toys",
		cost=costTable.scrap,
	},
	{level=5,invType="item",invName="RubberSpider",invResult="Base.RubberSpider",baseDuration=actionTime.mid,group="Toys",
		cost=costTable.clothSimple,
	},
	{level=5,invType="item",invName="Pillow_Happyface",invResult="Base.Pillow_Happyface",baseDuration=actionTime.mid,group="Toys",
		cost=costTable.cloth,
	},
	{level=5,invType="item",invName="Dice_20",invResult="Base.Dice_20",baseDuration=actionTime.mid,group="Toys",
		cost=costTable.woodSimple,
	},
	{level=5,invType="item",invName="CookieJar_Bear",invResult="Base.CookieJar_Bear",baseDuration=actionTime.mid,group="Toys",
		cost=costTable.scrapSimple,
	},
	{level=5,invType="item",invName="Glasses_OldWeldingGoggles",invResult="Base.Glasses_OldWeldingGoggles",baseDuration=actionTime.mid,group="Costumes",
		cost=costTable.scrap,
	},
	{level=5,invType="item",invName="Hat_Jay",invResult="Base.Hat_Jay",baseDuration=actionTime.mid,group="Costumes",
		cost=costTable.costume,
	},
	{level=5,invType="item",invName="MetalToyRocket",invResult="Lifestyle.MetalToyRocket",baseDuration=actionTime.mid,group="Toys",
		cost=costTable.scrap,
	},
	-- level 4 - 9
	{level=4,invType="item",invName="WoodToyRabbit",invResult="Lifestyle.WoodToyRabbit",baseDuration=actionTime.mid,group="Toys",
		cost=costTable.wood,
	},
	{level=4,invType="item",invName="WoodToyCamper",invResult="Lifestyle.WoodToyCamper",baseDuration=actionTime.mid,group="Toys",
		cost=costTable.wood,
	},
	{level=4,invType="item",invName="Rubberducky",invResult="Base.Rubberducky",baseDuration=actionTime.mid,group="Toys",
		cost=costTable.scrapSimple,
	},
	{level=4,invType="item",invName="ChristmasWreath",invResult="Base.ChristmasWreath",baseDuration=actionTime.mid,group="Toys",
		cost=costTable.cloth,
	},
	{level=4,invType="item",invName="Hat_Wizard",invResult="Base.Hat_Wizard",baseDuration=actionTime.mid,group="Costumes",
		cost=costTable.costume,
	},
	{level=4,invType="item",invName="BunnySuitBlack",invResult="Base.BunnySuitBlack",baseDuration=actionTime.midlong,group="Costumes",
		cost=costTable.costume,
	},
	{level=4,invType="item",invName="BunnyTail",invResult="Base.BunnyTail",baseDuration=actionTime.mid,group="Costumes",
		cost=costTable.cloth,
	},
	{level=4,invType="item",invName="Hat_BunnyEarsWhite",invResult="Base.Hat_BunnyEarsWhite",baseDuration=actionTime.mid,group="Costumes",
		cost=costTable.cloth,
	},
	{level=4,invType="item",invName="ToothpasteCurio",invResult="Lifestyle.ToothpasteCurio",baseDuration=actionTime.midlong,group="Curios",
		cost={
			["Base.ScrapMetal"]=6,
			["Base.Toothpaste"]=1,
			["Base.Glue"]=2,
			["Base.DryerLint"]=3,
		},
	},
	-- level 3 - 7
	{level=3,invType="item",invName="Pillow_Heart",invResult="Base.Pillow_Heart",baseDuration=actionTime.midshort,group="Toys",
		cost=costTable.clothSimple,
	},
	{level=3,invType="item",invName="HobbyHorse",invResult="Base.HobbyHorse",baseDuration=actionTime.mid,group="Curios",
		cost={
			["Base.Plank"]=3,
			["Base.WoodenStick2"]=2,
			["Base.Woodglue"]=4,
			["Base.Nails"]=6,
		},
	},
	{level=3,invType="item",invName="Glasses_Groucho",invResult="Base.Glasses_Groucho",baseDuration=actionTime.midshort,group="Costumes",
		cost=costTable.scrapSimple,
	},
	{level=3,invType="item",invName="Glasses_Cosmetic_MonocleLeft",invResult="Base.Glasses_Cosmetic_MonocleLeft",baseDuration=actionTime.midshort,group="Costumes",
		cost=costTable.scrapSimple,
	},
	{level=3,invType="item",invName="WoodToyHelicopter",invResult="Lifestyle.WoodToyHelicopter",baseDuration=actionTime.midshort,group="Toys",
		cost=costTable.woodSimple,
	},
	{level=3,invType="item",invName="ClothToyPenguin",invResult="Lifestyle.ClothToyPenguin",baseDuration=actionTime.midshort,group="Toys",
		cost=costTable.clothSimple,
	},
	{level=3,invType="item",invName="ToyChicken",invResult="Lifestyle.ToyChicken",baseDuration=actionTime.midlong,group="Curios",
		cost={
			["Base.ScrapMetal"]=6,
			["Base.Amplifier"]=1,
		},
	},
	-- level 2 - 9
	{level=2,invType="item",invName="ToyNewtonCradle",invResult="Lifestyle.ToyNewtonCradle",baseDuration=actionTime.midshort,group="Toys",
		cost=costTable.scrapSimple,
	},
	{level=2,invType="item",invName="WoodToyPlane",invResult="Lifestyle.WoodToyPlane",baseDuration=actionTime.midshort,group="Toys",
		cost=costTable.woodSimple,
	},
	{level=2,invType="item",invName="Pillow_Star",invResult="Base.Pillow_Star",baseDuration=actionTime.midshort,group="Toys",
		cost=costTable.clothSimple,
	},
	{level=2,invType="item",invName="DogChew",invResult="Base.DogChew",baseDuration=actionTime.midshort,group="Toys",
		cost=costTable.scrapSimple,
	},
	{level=2,invType="item",invName="HalloweenCandyBucket",invResult="Base.HalloweenCandyBucket",baseDuration=actionTime.midshort,group="Toys",
		cost=costTable.scrapSimple,
	},
	{level=2,invType="item",invName="Hat_Cowboy_Plastic",invResult="Base.Hat_Cowboy_Plastic",baseDuration=actionTime.midshort,group="Costumes",
		cost=costTable.costumeSimple,
	},
	{level=2,invType="item",invName="Hat_HalloweenMaskPumpkin",invResult="Base.Hat_HalloweenMaskPumpkin",baseDuration=actionTime.midshort,group="Costumes",
		cost=costTable.costumeSimple,
	},
	{level=2,invType="item",invName="Glasses_3dGlasses",invResult="Base.Glasses_3dGlasses",baseDuration=actionTime.midshort,group="Costumes",
		cost=costTable.scrapSimple,
	},
	{level=2,invType="item",invName="UmbrellaHat",invResult="Lifestyle.UmbrellaHat",baseDuration=actionTime.mid,group="Curios",
		cost=costTable.costume,
	},
	-- level 1 - 10
	{level=1,invType="item",invName="ToyCar",invResult="Base.ToyCar",baseDuration=actionTime.short,group="Toys",
		cost=costTable.scrapVerySimple,
	},
	{level=1,invType="item",invName="ToyPlane",invResult="Base.ToyPlane",baseDuration=actionTime.short,group="Toys",
		cost=costTable.woodVerySimple,
	},
	{level=1,invType="item",invName="OujaBoard",invResult="Base.OujaBoard",baseDuration=actionTime.short,group="Toys",
		cost=costTable.woodVerySimple,
	},
	{level=1,invType="item",invName="ToyBear_Crafted_Cotton",invResult="Base.ToyBear_Crafted_Cotton",baseDuration=actionTime.short,group="Toys",
		cost=costTable.clothVerySimple,
	},
	{level=1,invType="item",invName="Dice",invResult="Base.Dice",baseDuration=actionTime.short,group="Toys",
		cost=costTable.woodVerySimple,
	},
	{level=1,invType="item",invName="Glasses_Novelty_Xray",invResult="Base.Glasses_Novelty_Xray",baseDuration=actionTime.short,group="Costumes",
		cost=costTable.scrapVerySimple,
	},
	{level=1,invType="item",invName="Glasses_Round_HoloSkulls",invResult="Base.Glasses_Round_HoloSkulls",baseDuration=actionTime.short,group="Costumes",
		cost=costTable.costumeVerySimple,
	},
	{level=1,invType="item",invName="Hat_Antlers",invResult="Base.Hat_Antlers",baseDuration=actionTime.short,group="Costumes",
		cost=costTable.costumeVerySimple,
	},
	{level=1,invType="item",invName="WoodenToyPlane",invResult="Lifestyle.WoodenToyPlane",baseDuration=actionTime.short,group="Toys",
		cost=costTable.woodVerySimple,
	},
	{level=1,invType="item",invName="WoodToyHorse",invResult="Lifestyle.WoodToyHorse",baseDuration=actionTime.short,group="Toys",
		cost={
			["Base.Plank"]=1,
			["Base.WoodenStick2"]=1,
			["Base.Woodglue"]=2,
			["Base.Nails"]=4,
		},
	},
	-- level 0 - 13
	{level=0,invType="item",invName="WoodToyTank",invResult="Lifestyle.WoodToyTank",baseDuration=actionTime.shortest,group="Toys",
		cost=costTable.woodVerySimple,
	},
	{level=0,invType="item",invName="Doll",invResult="Base.Doll",baseDuration=actionTime.shortest,group="Toys",
		cost=costTable.clothVerySimple,
	},
	{level=0,invType="item",invName="Bricktoys",invResult="Base.Bricktoys",baseDuration=actionTime.shortest,group="Toys",
		cost=costTable.woodVerySimple,
	},
	{level=0,invType="item",invName="MetalToyDog",invResult="Lifestyle.MetalToyDog",baseDuration=actionTime.shortest,group="Toys",
		cost=costTable.scrapVerySimple,
	},

	{level=0,invType="item",invName="Bell",invResult="Base.Bell",baseDuration=actionTime.shortest,group="Curios",
		cost={
			["Base.SmallHandle"]=1,
			["Base.BrassScrap"]=2,
		},
	},
	{level=0,invType="obj",invName="DrinkingBuddy",invResult="LS_Inventions_12",baseDuration=actionTime.short,group="Curios",
		cost=costTable.curioVerySimple,
	},
	
	{level=0,invType="item",invName="Hat_FurryEars",invResult="Base.Hat_FurryEars",baseDuration=actionTime.shortest,group="Costumes",
		cost=costTable.costumeVerySimple,
	},
	{level=0,invType="item",invName="Hat_GoldStar",invResult="Base.Hat_GoldStar",baseDuration=actionTime.shortest,group="Costumes",
		cost=costTable.costumeVerySimple,
	},
	{level=0,invType="item",invName="Hat_JokeKnife",invResult="Base.Hat_JokeKnife",baseDuration=actionTime.shortest,group="Costumes",
		cost=costTable.costumeVerySimple,
	},
	{level=0,invType="item",invName="Hat_PartyHat_Stars",invResult="Base.Hat_PartyHat_Stars",baseDuration=actionTime.shortest,group="Costumes",
		cost=costTable.costumeVerySimple,
	},
	{level=0,invType="item",invName="CatToy",invResult="Base.CatToy",baseDuration=actionTime.shortest,group="Toys",
		cost=costTable.clothVerySimple,
	},
	{level=0,invType="item",invName="Yoyo",invResult="Base.Yoyo",baseDuration=actionTime.shortest,group="Toys",
		cost={
			["Base.Plank"]=1,
			["Base.Thread"]=1,
		},
	},
	{level=0,invType="item",invName="WoodToyTrain",invResult="Lifestyle.WoodToyTrain",baseDuration=actionTime.shortest,group="Toys",
		cost=costTable.woodVerySimple,
	},
}
