local env = _G.NMWalkmanWindowEnv
setfenv(1, env)

local function S(value)
    if NMFancyDeviceUiScale and NMFancyDeviceUiScale.scaleValue then
        return NMFancyDeviceUiScale.scaleValue(value)
    end
    return math.floor((tonumber(value) or 0) + 0.5)
end

PANEL_W = PANEL_W or 469
PANEL_H = PANEL_H or 285
BG_X = BG_X or 15
BG_Y = BG_Y or 16
BG_W = BG_W or 437
BG_H = BG_H or 268
HEADER_X = HEADER_X or BG_X
HEADER_Y = HEADER_Y or BG_Y
HEADER_W = HEADER_W or BG_W
HEADER_H = HEADER_H or 41
DEFAULT_RIGHT_MARGIN = DEFAULT_RIGHT_MARGIN or 24
EXPANDED_BOTTOM_MARGIN = EXPANDED_BOTTOM_MARGIN or 10
DRAG_THRESHOLD_X = DRAG_THRESHOLD_X or 6
ANIMATION_DURATION_MS = ANIMATION_DURATION_MS or 300
PLAY_BUTTON_ANIMATION_DURATION_MS = PLAY_BUTTON_ANIMATION_DURATION_MS or 300
PREV_BUTTON_ANIMATION_PHASE_MS = PREV_BUTTON_ANIMATION_PHASE_MS or 150
CLOSE_INSET_X = CLOSE_INSET_X or 9
CLOSE_INSET_Y = CLOSE_INSET_Y or 9
CLOSE_W = CLOSE_W or 10
CLOSE_H = CLOSE_H or 10
SETTINGS_GAP_Y = SETTINGS_GAP_Y or 8
PLAY_BUTTON_X = PLAY_BUTTON_X or 57
PLAY_BUTTON_UP_Y = PLAY_BUTTON_UP_Y or 1
PLAY_BUTTON_DOWN_Y = PLAY_BUTTON_DOWN_Y or 12
PLAY_BUTTON_W = PLAY_BUTTON_W or 54
PLAY_BUTTON_H = PLAY_BUTTON_H or 20
PLAY_BUTTON_HIT_X = PLAY_BUTTON_HIT_X or PLAY_BUTTON_X
PLAY_BUTTON_HIT_Y = PLAY_BUTTON_HIT_Y or 0
PLAY_BUTTON_HIT_W = PLAY_BUTTON_HIT_W or 54
PLAY_BUTTON_HIT_H = PLAY_BUTTON_HIT_H or 36
PREV_BUTTON_MARGIN_X = PREV_BUTTON_MARGIN_X or 6
PREV_BUTTON_X = PREV_BUTTON_X or PLAY_BUTTON_X + PLAY_BUTTON_W + PREV_BUTTON_MARGIN_X
PREV_BUTTON_UP_Y = PREV_BUTTON_UP_Y or PLAY_BUTTON_UP_Y
PREV_BUTTON_DOWN_Y = PREV_BUTTON_DOWN_Y or PLAY_BUTTON_DOWN_Y
PREV_BUTTON_W = PREV_BUTTON_W or 54
PREV_BUTTON_H = PREV_BUTTON_H or 20
PREV_BUTTON_HIT_X = PREV_BUTTON_HIT_X or PREV_BUTTON_X
PREV_BUTTON_HIT_Y = PREV_BUTTON_HIT_Y or 0
PREV_BUTTON_HIT_W = PREV_BUTTON_HIT_W or 54
PREV_BUTTON_HIT_H = PREV_BUTTON_HIT_H or 36
NEXT_BUTTON_MARGIN_X = NEXT_BUTTON_MARGIN_X or -2
NEXT_BUTTON_X = NEXT_BUTTON_X or PREV_BUTTON_X + PREV_BUTTON_W + NEXT_BUTTON_MARGIN_X
NEXT_BUTTON_UP_Y = NEXT_BUTTON_UP_Y or PREV_BUTTON_UP_Y
NEXT_BUTTON_DOWN_Y = NEXT_BUTTON_DOWN_Y or PREV_BUTTON_DOWN_Y
NEXT_BUTTON_W = NEXT_BUTTON_W or 54
NEXT_BUTTON_H = NEXT_BUTTON_H or 20
NEXT_BUTTON_HIT_X = NEXT_BUTTON_HIT_X or NEXT_BUTTON_X
NEXT_BUTTON_HIT_Y = NEXT_BUTTON_HIT_Y or 0
NEXT_BUTTON_HIT_W = NEXT_BUTTON_HIT_W or 54
NEXT_BUTTON_HIT_H = NEXT_BUTTON_HIT_H or 36
VOLUME_WHEEL_X = VOLUME_WHEEL_X or -4
VOLUME_WHEEL_Y = VOLUME_WHEEL_Y or HEADER_Y + HEADER_H + 10
VOLUME_WHEEL_W = VOLUME_WHEEL_W or 85
VOLUME_WHEEL_H = VOLUME_WHEEL_H or 85
VOLUME_WHEEL_HIT_X = VOLUME_WHEEL_HIT_X or 1
VOLUME_WHEEL_HIT_W = VOLUME_WHEEL_HIT_W or 25
VOLUME_WHEEL_HIT_H = VOLUME_WHEEL_HIT_H or 85
VOLUME_WHEEL_MIN_ANGLE = VOLUME_WHEEL_MIN_ANGLE or -135
VOLUME_WHEEL_MAX_ANGLE = VOLUME_WHEEL_MAX_ANGLE or 135
VOLUME_LABEL_HIDE_DELAY_MS = VOLUME_LABEL_HIDE_DELAY_MS or 3000
VOLUME_DRAG_DISPATCH_MIN_MS = VOLUME_DRAG_DISPATCH_MIN_MS or 80
VOLUME_CLICK_SOUND_MIN_MS = VOLUME_CLICK_SOUND_MIN_MS or 35
VOLUME_LABEL_GAP_X = VOLUME_LABEL_GAP_X or 8
VOLUME_WHEEL_DRAG_SPAN_PX = VOLUME_WHEEL_DRAG_SPAN_PX or 180
SLOT_SIZE = SLOT_SIZE or 40
SLOT_STACK_X = SLOT_STACK_X or BG_X + 21
SLOT_STACK_Y = SLOT_STACK_Y or HEADER_Y + HEADER_H + 14
SLOT_STACK_GAP_Y = SLOT_STACK_GAP_Y or 6
BATTERY_METER_X = BATTERY_METER_X or SLOT_STACK_X - 6
BATTERY_METER_W = BATTERY_METER_W or 3
BATTERY_METER_H = BATTERY_METER_H or SLOT_SIZE
BATTERY_METER_BG = BATTERY_METER_BG or { a = 0.95, r = 0.05, g = 0.05, b = 0.05 }
BATTERY_METER_FILL = BATTERY_METER_FILL or { a = 0.95, r = 0.20, g = 0.80, b = 0.20 }
BATTERY_METER_EMPTY = BATTERY_METER_EMPTY or { a = 0.95, r = 0.80, g = 0.14, b = 0.14 }
LOOP_BUTTON_X = LOOP_BUTTON_X or 4
LOOP_BUTTON_UP_X = LOOP_BUTTON_UP_X or LOOP_BUTTON_X
LOOP_BUTTON_DOWN_X = LOOP_BUTTON_DOWN_X or LOOP_BUTTON_X + 9
LOOP_BUTTON_Y = LOOP_BUTTON_Y or PANEL_H - 31 - 50
LOOP_BUTTON_W = LOOP_BUTTON_W or 16
LOOP_BUTTON_H = LOOP_BUTTON_H or 50
LOOP_BUTTON_ANIMATION_PHASE_MS = LOOP_BUTTON_ANIMATION_PHASE_MS or 150
LOOP_ICON_X = LOOP_ICON_X or BG_X
LOOP_ICON_ALPHA = LOOP_ICON_ALPHA or 0.3
STOP_BUTTON_X = STOP_BUTTON_X or BG_X + 63
STOP_BUTTON_Y = STOP_BUTTON_Y or BG_Y + 9
STOP_BUTTON_W = STOP_BUTTON_W or 10
STOP_BUTTON_H = STOP_BUTTON_H or 10
CASSETTE_DISPLAY_X = CASSETTE_DISPLAY_X or 128
CASSETTE_DISPLAY_Y = CASSETTE_DISPLAY_Y or 119
CASSETTE_DISPLAY_W = CASSETTE_DISPLAY_W or 256
CASSETTE_DISPLAY_H = CASSETTE_DISPLAY_H or 156
CASSETTE_SPOOL_A_X = CASSETTE_SPOOL_A_X or CASSETTE_DISPLAY_X + 62
CASSETTE_SPOOL_A_Y = CASSETTE_SPOOL_A_Y or CASSETTE_DISPLAY_Y + 55
CASSETTE_SPOOL_B_X = CASSETTE_SPOOL_B_X or CASSETTE_DISPLAY_X + 163
CASSETTE_SPOOL_B_Y = CASSETTE_SPOOL_B_Y or CASSETTE_DISPLAY_Y + 55
CASSETTE_SPOOL_W = CASSETTE_SPOOL_W or 30
CASSETTE_SPOOL_H = CASSETTE_SPOOL_H or 30
CASSETTE_SPOOL_DEGREES_PER_SECOND = CASSETTE_SPOOL_DEGREES_PER_SECOND or 72
CASSETTE_LABEL_X = CASSETTE_LABEL_X or CASSETTE_DISPLAY_X + 20
CASSETTE_LABEL_Y = CASSETTE_LABEL_Y or CASSETTE_DISPLAY_Y + 26
CASSETTE_LABEL_W = CASSETTE_LABEL_W or 216
CASSETTE_LABEL_H = CASSETTE_LABEL_H or 21
CASSETTE_LABEL_LORE_OFFSET_Y = CASSETTE_LABEL_LORE_OFFSET_Y or 65
CASSETTE_LABEL_TEXT_PAD_X = CASSETTE_LABEL_TEXT_PAD_X or 5
CASSETTE_LABEL_TEXT_COLOR = CASSETTE_LABEL_TEXT_COLOR or { a = 1.0, r = 0.08, g = 0.08, b = 0.08 }
CASSETTE_LABEL_BG = CASSETTE_LABEL_BG or { a = 1.0, r = 1.0, g = 1.0, b = 1.0 }
LID_W = LID_W or 371
LID_H = LID_H or 227
LID_RIGHT_INSET = LID_RIGHT_INSET or 16
LID_BOTTOM_INSET = LID_BOTTOM_INSET or 1
LID_OPEN_SHRINK_H = LID_OPEN_SHRINK_H or 60
LID_X = LID_X or PANEL_W - LID_RIGHT_INSET - LID_W
LID_Y = LID_Y or PANEL_H - LID_BOTTOM_INSET - LID_H
LID_OPEN_H = LID_OPEN_H or LID_H - LID_OPEN_SHRINK_H
LID_OPEN_Y = LID_OPEN_Y or LID_Y + LID_OPEN_SHRINK_H
LID_ANIMATION_DURATION_MS = LID_ANIMATION_DURATION_MS or 420
LID_EDGE_W = LID_EDGE_W or 371
LID_EDGE_H = LID_EDGE_H or 14
SIDE_W = SIDE_W or 68
SIDE_H = SIDE_H or 227
SIDE_LEFT_INSET = SIDE_LEFT_INSET or 16
SIDE_BOTTOM_INSET = SIDE_BOTTOM_INSET or 1
SIDE_X = SIDE_X or SIDE_LEFT_INSET
SIDE_Y = SIDE_Y or PANEL_H - SIDE_BOTTOM_INSET - SIDE_H
LID_ARROW_Y_OFFSET = LID_ARROW_Y_OFFSET or 0
LID_ARROW_W = LID_ARROW_W or LID_W
LID_ARROW_H = LID_ARROW_H or 75
LID_INGRESS_W = LID_INGRESS_W or 367
LID_INGRESS_H = LID_INGRESS_H or 57
LID_INGRESS_BORDER = LID_INGRESS_BORDER or { a = 1.0, r = 1.0, g = 1.0, b = 1.0 }
PERSISTED_UI_STATE_KEY = PERSISTED_UI_STATE_KEY or "NMWalkmanUIState"
RESTORE_RETRY_WINDOW_MS = RESTORE_RETRY_WINDOW_MS or 8000
BACKPLATE_BASE_TEXTURE_PATH = BACKPLATE_BASE_TEXTURE_PATH or "media/textures/UI/Walkman/NM_UI_Walkman01.png"
BACKPLATE_BASE_DARK_TEXTURE_PATH = BACKPLATE_BASE_DARK_TEXTURE_PATH or "media/textures/UI/Walkman/NM_UI_Walkman01_Dark.png"
BACKPLATE_SLOT_BG_TEXTURE_PATH = BACKPLATE_SLOT_BG_TEXTURE_PATH or "media/textures/UI/Walkman/NM_UI_WalkmanSlotBG.png"
LID_EDGE_TEXTURE_PATH = LID_EDGE_TEXTURE_PATH or "media/textures/UI/Walkman/NM_UI_Walkman_Lid_Edge.png"
CLOSE_TEXTURE_PATH = CLOSE_TEXTURE_PATH or "media/textures/UI/Walkman/NM_UI_Walkman_Close.png"
PLAY_BUTTON_TEXTURE_PATH = PLAY_BUTTON_TEXTURE_PATH or "media/textures/UI/Walkman/NM_UI_Button_Play.png"
PREV_BUTTON_TEXTURE_PATH = PREV_BUTTON_TEXTURE_PATH or "media/textures/UI/Walkman/NM_UI_Button_Prev.png"
NEXT_BUTTON_TEXTURE_PATH = NEXT_BUTTON_TEXTURE_PATH or "media/textures/UI/Walkman/NM_UI_Button_Next.png"
PLAY_BUTTON_DARK_TEXTURE_PATH = PLAY_BUTTON_DARK_TEXTURE_PATH or "media/textures/UI/Walkman/NM_UI_Button_Play_Dark.png"
PREV_BUTTON_DARK_TEXTURE_PATH = PREV_BUTTON_DARK_TEXTURE_PATH or "media/textures/UI/Walkman/NM_UI_Button_Prev_Dark.png"
NEXT_BUTTON_DARK_TEXTURE_PATH = NEXT_BUTTON_DARK_TEXTURE_PATH or "media/textures/UI/Walkman/NM_UI_Button_Next_Dark.png"
VOLUME_WHEEL_TEXTURE_PATH = VOLUME_WHEEL_TEXTURE_PATH or "media/textures/UI/Walkman/NM_UI_VolumeWheel.png"
LOOP_BUTTON_TEXTURE_PATH = LOOP_BUTTON_TEXTURE_PATH or "media/textures/UI/Walkman/NM_UI_Button_Repeat.png"
LOOP_ICON_NONE_TEXTURE_PATH = LOOP_ICON_NONE_TEXTURE_PATH or "media/textures/UI/Walkman/NM_UI_Walkman_RepeatNone.png"
LOOP_ICON_SONG_TEXTURE_PATH = LOOP_ICON_SONG_TEXTURE_PATH or "media/textures/UI/Walkman/NM_UI_Walkman_RepeatSong.png"
LOOP_ICON_ALBUM_TEXTURE_PATH = LOOP_ICON_ALBUM_TEXTURE_PATH or "media/textures/UI/Walkman/NM_UI_Walkman_RepeatAlbum.png"
STOP_BUTTON_TEXTURE_PATH = STOP_BUTTON_TEXTURE_PATH or "media/textures/UI/Walkman/NM_UI_Button_Stop.png"
SPOOL_TEXTURE_PATH = SPOOL_TEXTURE_PATH or "media/textures/UI/Walkman/NM_UI_Walkman_Spool.png"
WALKMAN_UI_VARIANT_FALLBACK = WALKMAN_UI_VARIANT_FALLBACK or "Blue"
WALKMAN_UI_TEXTURES_BY_VARIANT = WALKMAN_UI_TEXTURES_BY_VARIANT or {}
UI_TEXTURES = UI_TEXTURES or {}

WALKMAN_LAYOUT_KEYS = WALKMAN_LAYOUT_KEYS or {
    "PANEL_W", "PANEL_H", "BG_X", "BG_Y", "BG_W", "BG_H", "HEADER_X", "HEADER_Y", "HEADER_W", "HEADER_H",
    "DEFAULT_RIGHT_MARGIN", "EXPANDED_BOTTOM_MARGIN", "DRAG_THRESHOLD_X", "CLOSE_INSET_X", "CLOSE_INSET_Y", "CLOSE_W", "CLOSE_H", "SETTINGS_GAP_Y",
    "PLAY_BUTTON_X", "PLAY_BUTTON_UP_Y", "PLAY_BUTTON_DOWN_Y", "PLAY_BUTTON_W", "PLAY_BUTTON_H", "PLAY_BUTTON_HIT_X", "PLAY_BUTTON_HIT_Y", "PLAY_BUTTON_HIT_W", "PLAY_BUTTON_HIT_H",
    "PREV_BUTTON_MARGIN_X", "PREV_BUTTON_X", "PREV_BUTTON_UP_Y", "PREV_BUTTON_DOWN_Y", "PREV_BUTTON_W", "PREV_BUTTON_H", "PREV_BUTTON_HIT_X", "PREV_BUTTON_HIT_Y", "PREV_BUTTON_HIT_W", "PREV_BUTTON_HIT_H",
    "NEXT_BUTTON_MARGIN_X", "NEXT_BUTTON_X", "NEXT_BUTTON_UP_Y", "NEXT_BUTTON_DOWN_Y", "NEXT_BUTTON_W", "NEXT_BUTTON_H", "NEXT_BUTTON_HIT_X", "NEXT_BUTTON_HIT_Y", "NEXT_BUTTON_HIT_W", "NEXT_BUTTON_HIT_H",
    "VOLUME_WHEEL_X", "VOLUME_WHEEL_Y", "VOLUME_WHEEL_W", "VOLUME_WHEEL_H", "VOLUME_WHEEL_HIT_X", "VOLUME_WHEEL_HIT_W", "VOLUME_WHEEL_HIT_H",
    "VOLUME_LABEL_GAP_X", "VOLUME_WHEEL_DRAG_SPAN_PX", "SLOT_SIZE", "SLOT_STACK_X", "SLOT_STACK_Y", "SLOT_STACK_GAP_Y",
    "BATTERY_METER_X", "BATTERY_METER_W", "BATTERY_METER_H", "LOOP_BUTTON_X", "LOOP_BUTTON_UP_X", "LOOP_BUTTON_DOWN_X", "LOOP_BUTTON_Y", "LOOP_BUTTON_W", "LOOP_BUTTON_H",
    "LOOP_ICON_X", "STOP_BUTTON_X", "STOP_BUTTON_Y", "STOP_BUTTON_W", "STOP_BUTTON_H", "CASSETTE_DISPLAY_X", "CASSETTE_DISPLAY_Y", "CASSETTE_DISPLAY_W", "CASSETTE_DISPLAY_H",
    "CASSETTE_SPOOL_A_X", "CASSETTE_SPOOL_A_Y", "CASSETTE_SPOOL_B_X", "CASSETTE_SPOOL_B_Y", "CASSETTE_SPOOL_W", "CASSETTE_SPOOL_H",
    "CASSETTE_LABEL_X", "CASSETTE_LABEL_Y", "CASSETTE_LABEL_W", "CASSETTE_LABEL_H", "CASSETTE_LABEL_LORE_OFFSET_Y", "CASSETTE_LABEL_TEXT_PAD_X",
    "LID_W", "LID_H", "LID_RIGHT_INSET", "LID_BOTTOM_INSET", "LID_OPEN_SHRINK_H", "LID_X", "LID_Y", "LID_OPEN_H", "LID_OPEN_Y", "LID_EDGE_W", "LID_EDGE_H",
    "SIDE_W", "SIDE_H", "SIDE_LEFT_INSET", "SIDE_BOTTOM_INSET", "SIDE_X", "SIDE_Y", "LID_ARROW_Y_OFFSET", "LID_ARROW_W", "LID_ARROW_H", "LID_INGRESS_W", "LID_INGRESS_H"
}

WALKMAN_LAYOUT_BASE = WALKMAN_LAYOUT_BASE or {}
for i = 1, #WALKMAN_LAYOUT_KEYS do
    local key = WALKMAN_LAYOUT_KEYS[i]
    if WALKMAN_LAYOUT_BASE[key] == nil then
        WALKMAN_LAYOUT_BASE[key] = env[key]
    end
end

function refreshWalkmanLayoutMetrics()
    for i = 1, #WALKMAN_LAYOUT_KEYS do
        local key = WALKMAN_LAYOUT_KEYS[i]
        local base = WALKMAN_LAYOUT_BASE[key]
        if base ~= nil then
            env[key] = S(base)
        end
    end
end

refreshWalkmanLayoutMetrics()
