-- Generated by tools/d2_source_package.py; exact installed source provenance retained.
SAO=SAO or {}
SAO.SourcePackageManifest={schema="sao.owned-source-package/1",packageId="SurvivorAwareness",sources={
["LifestyleHobbies"]={sentinel="media/SAOSources/LifestyleHobbies/package.txt",seal="b53578004cccd49adc63c65dc05df7d635f3241fb65960029c2dc3bebacdcfe3",root="media/SAOSources/LifestyleHobbies"},
["NewMusic"]={sentinel="media/SAOSources/NewMusic/package.txt",seal="f77bc78b45885332d3b0ec923d6d7b7a3da4cbc34045d544b9c1e140b1bf9b74",root="media/SAOSources/NewMusic"},
["ComputerModkum"]={sentinel="media/SAOSources/ComputerModkum/package.txt",seal="b875312c675aae4d0caba0ed7dea302076b6f57ef42914623ff57d202e8987d0",root="media/SAOSources/ComputerModkum"},
["ProjectArcade"]={sentinel="media/SAOSources/ProjectArcade/package.txt",seal="cfa910924a973e253587090b30c9d7950df21f9f4db075a16ba260019f9581b8",root="media/SAOSources/ProjectArcade"},
["FWOFitnessWorkoutOverhaul"]={sentinel="media/SAOSources/FWOFitnessWorkoutOverhaul/package.txt",seal="6ccff1e6190e5004180826aaa7eb63cc2209e0b0e3648bf1d5e2c72e041ed82d",root="media/SAOSources/FWOFitnessWorkoutOverhaul"},
["FWOBenchPressTreadmill"]={sentinel="media/SAOSources/FWOBenchPressTreadmill/package.txt",seal="afc25ea32fcfa93073c6ec107ce79a57771465106dfa40fd232c7f46e9942229",root="media/SAOSources/FWOBenchPressTreadmill"},
["KnoxAquarium"]={sentinel="media/SAOSources/KnoxAquarium/package.txt",seal="270f46d64aeeae8576ec035d8861c2f65a5bd1e0e4653ae120c369c59f370336",root="media/SAOSources/KnoxAquarium"},
}}
return SAO.SourcePackageManifest
