-- Generated by tools/weekone_sandbox_controls.py from the pinned Week One option fragment.
SAO = SAO or {}
SAO.WeekOneSandboxPages = {schema="sao.weekone-sandbox-pages/1", options={
["BanditsWeekOne.StartTime"]={sourceId="BanditsWeekOne",originalPage="BanditsWeekOne",ownedPage="SAO_WeekOne_Start",preferOwned=true,hasTooltip=true},
["BanditsWeekOne.StartBabe"]={sourceId="BanditsWeekOne",originalPage="BanditsWeekOne",ownedPage="SAO_WeekOne_Start",preferOwned=true,hasTooltip=true},
["BanditsWeekOne.StartRide"]={sourceId="BanditsWeekOne",originalPage="BanditsWeekOne",ownedPage="SAO_WeekOne_Start",preferOwned=true,hasTooltip=true},
["BanditsWeekOne.InhabitantsPopMultiplier"]={sourceId="BanditsWeekOne",originalPage="BanditsWeekOne",ownedPage="SAO_WeekOne_People",preferOwned=true,hasTooltip=false},
["BanditsWeekOne.StreetsPopMultiplier"]={sourceId="BanditsWeekOne",originalPage="BanditsWeekOne",ownedPage="SAO_WeekOne_People",preferOwned=true,hasTooltip=false},
["BanditsWeekOne.ArmyPopMultiplier"]={sourceId="BanditsWeekOne",originalPage="BanditsWeekOne",ownedPage="SAO_WeekOne_People",preferOwned=true,hasTooltip=false},
["BanditsWeekOne.BanditsPopMultiplier"]={sourceId="BanditsWeekOne",originalPage="BanditsWeekOne",ownedPage="SAO_WeekOne_People",preferOwned=true,hasTooltip=false},
["BanditsWeekOne.InhabitantsPistolChance"]={sourceId="BanditsWeekOne",originalPage="BanditsWeekOne",ownedPage="SAO_WeekOne_People",preferOwned=true,hasTooltip=false},
["BanditsWeekOne.StreetsPistolChance"]={sourceId="BanditsWeekOne",originalPage="BanditsWeekOne",ownedPage="SAO_WeekOne_People",preferOwned=true,hasTooltip=false},
["BanditsWeekOne.VehiclesMax"]={sourceId="BanditsWeekOne",originalPage="BanditsWeekOne",ownedPage="SAO_WeekOne_Roads",preferOwned=true,hasTooltip=false},
["BanditsWeekOne.VehiclesSpeed"]={sourceId="BanditsWeekOne",originalPage="BanditsWeekOne",ownedPage="SAO_WeekOne_Roads",preferOwned=true,hasTooltip=false},
["BanditsWeekOne.PoliceCooldown"]={sourceId="BanditsWeekOne",originalPage="BanditsWeekOne",ownedPage="SAO_WeekOne_Response",preferOwned=true,hasTooltip=false},
["BanditsWeekOne.SWATCooldown"]={sourceId="BanditsWeekOne",originalPage="BanditsWeekOne",ownedPage="SAO_WeekOne_Response",preferOwned=true,hasTooltip=false},
["BanditsWeekOne.MedicsCooldown"]={sourceId="BanditsWeekOne",originalPage="BanditsWeekOne",ownedPage="SAO_WeekOne_Response",preferOwned=true,hasTooltip=false},
["BanditsWeekOne.HazmatCooldown"]={sourceId="BanditsWeekOne",originalPage="BanditsWeekOne",ownedPage="SAO_WeekOne_Response",preferOwned=true,hasTooltip=false},
["BanditsWeekOne.FiremanCooldown"]={sourceId="BanditsWeekOne",originalPage="BanditsWeekOne",ownedPage="SAO_WeekOne_Response",preferOwned=true,hasTooltip=false},
["BanditsWeekOne.PriceMultiplier"]={sourceId="BanditsWeekOne",originalPage="BanditsWeekOne",ownedPage="SAO_WeekOne_Exchange",preferOwned=true,hasTooltip=false},
["BanditsWeekOne.PriceInflation"]={sourceId="BanditsWeekOne",originalPage="BanditsWeekOne",ownedPage="SAO_WeekOne_Exchange",preferOwned=true,hasTooltip=false},
["BanditsWeekOne.EventFinalSolution"]={sourceId="BanditsWeekOne",originalPage="BanditsWeekOne",ownedPage="SAO_WeekOne_Events",preferOwned=true,hasTooltip=true},
["BanditsWeekOne.EventBoeing"]={sourceId="BanditsWeekOne",originalPage="BanditsWeekOne",ownedPage="SAO_WeekOne_Events",preferOwned=true,hasTooltip=false},
["BanditsWeekOne.EventStrafe"]={sourceId="BanditsWeekOne",originalPage="BanditsWeekOne",ownedPage="SAO_WeekOne_Events",preferOwned=true,hasTooltip=false},
["BanditsWeekOne.EventBombing"]={sourceId="BanditsWeekOne",originalPage="BanditsWeekOne",ownedPage="SAO_WeekOne_Events",preferOwned=true,hasTooltip=false},
["BanditsWeekOne.EventGas"]={sourceId="BanditsWeekOne",originalPage="BanditsWeekOne",ownedPage="SAO_WeekOne_Events",preferOwned=true,hasTooltip=false},
["BanditsWeekOne.EventArson"]={sourceId="BanditsWeekOne",originalPage="BanditsWeekOne",ownedPage="SAO_WeekOne_Events",preferOwned=true,hasTooltip=false},
}}
return SAO.WeekOneSandboxPages
