"""The shipped world, read off the installed game for the sweep.

Two files are produced, both read from the game rather than invented:

  regions.lua   every town's `spawnpoints.lua`, each kept as its own
                spawn region, in the shape `SpawnRegionMgr` returns.
                The county sizes itself from the NUMBER of regions
                ([B38]), so collapsing eleven towns into one makes
                genesis build a county the map does not support.

  map.lua       the buildings and room names for every cell those
                towns occupy, out of the `.lotheader` files.

Neither is committed. They are the game's data, they are large, and
they are only meaningful against the install that produced them - so
they are written beside the sweep's other working files and rebuilt
when the game's maps are newer than the cache.

Each town's file defines `function SpawnPoints()`, so loading them in
sequence would leave only the last. Each is renamed as it is copied,
and the manager calls all of them.

THE CELL SIZE IS 256, and that is checked rather than assumed: every
spawn point in the shipped `spawnpoints.lua` files must land inside a
room of the cell that arithmetic puts it in. They land in livingrooms
and kitchens, which is what a spawn point is.

The `.lotheader` layout, read empirically and checked against the
strings in the file:

    "LOTH", int version, int tileCount, tileCount newline-terminated
    tile names, four ints, roomCount, then per room: name, level,
    rectCount, rects of (x, y, w, h), objectCount, objects of three
    ints. Then buildingCount and per building a room count and that
    many room indices. A fixed 1024-byte block follows, one byte per
    chunk - which is why "consumes the file exactly" was the wrong
    acceptance test for this reader.
"""
import pathlib
import re
import struct

CELL = 256


def maps_dir(game):
    return pathlib.Path(game) / "media" / "maps"


def towns(game):
    """(name, spawnpoints.lua) for every shipped map that has one."""
    out = []
    root = maps_dir(game)
    if not root.is_dir():
        return out
    for d in sorted(root.iterdir()):
        f = d / "spawnpoints.lua"
        if f.is_dir() or not f.exists():
            continue
        out.append((d.name, f))
    return out


def read_cell(path):
    """(rooms, buildings) out of one .lotheader, or None."""
    d = path.read_bytes()
    if d[:4] != b"LOTH":
        return None
    i = 8                      # "LOTH" and the version
    n = struct.unpack_from("<i", d, i)[0]
    i += 4
    for _ in range(n):         # the tile names
        i = d.find(b"\n", i) + 1
    i += 16                    # four ints nothing here reads

    def i32():
        nonlocal i
        v = struct.unpack_from("<i", d, i)[0]
        i += 4
        return v

    def line():
        nonlocal i
        e = d.find(b"\n", i)
        s = d[i:e].decode("utf-8", "replace")
        i = e + 1
        return s

    rooms = []
    for _ in range(i32()):
        name = line()
        i32()                                          # level
        boxes = [(i32(), i32(), i32(), i32()) for _ in range(i32())]
        for _ in range(i32()):                         # objects
            i32(); i32(); i32()
        rooms.append((name, boxes))
    buildings = [[i32() for _ in range(i32())] for _ in range(i32())]
    return rooms, buildings


def build(game, dest):
    """Write regions.lua and map.lua into `dest`. Returns a summary."""
    dest = pathlib.Path(dest)
    dest.mkdir(parents=True, exist_ok=True)
    found = towns(game)
    if not found:
        return None

    parts = ["-- Every shipped town's spawn points, each its own region.",
             "-- Generated by tools/sweep/world.py. Nothing here is chosen.",
             ""]
    calls, coords = [], []
    for k, (name, f) in enumerate(found):
        src = f.read_text(encoding="utf-8", errors="replace")
        fn = "SpawnPoints_%d" % k
        src = re.sub(r"\bfunction\s+SpawnPoints\s*\(", "function %s(" % fn, src)
        parts.append(src)
        calls.append((name, fn))
        for m in re.finditer(r"posX\s*=\s*(\d+)\s*,\s*posY\s*=\s*(\d+)", src):
            coords.append((int(m.group(1)), int(m.group(2))))
    parts.append("SpawnRegionMgr = { getSpawnRegions = function() return {")
    for name, fn in calls:
        parts.append('  { name = "%s", points = %s() },' % (name, fn))
    parts.append("} end }")
    (dest / "regions.lua").write_text("\n".join(parts), encoding="utf-8")

    # Every cell a spawn point sits in, plus a ring around it so a
    # survivor's comfort horizon is not a cliff edge.
    cells = set()
    for (x, y) in coords:
        cx, cy = x // CELL, y // CELL
        for dx in (-1, 0, 1):
            for dy in (-1, 0, 1):
                cells.add((cx + dx, cy + dy))

    by_name = [n for n, _ in found]
    out, rooms_total, cells_read = [], 0, 0
    for (cx, cy) in sorted(cells):
        p = None
        for name in by_name:
            q = maps_dir(game) / name / ("%d_%d.lotheader" % (cx, cy))
            if q.exists():
                p = q
                break
        if p is None:
            continue
        got = read_cell(p)
        if not got:
            continue
        cells_read += 1
        rooms, buildings = got
        ox, oy = cx * CELL, cy * CELL
        for members in buildings:
            names, minx, miny, maxx, maxy = [], None, None, 0, 0
            for ri in members:
                if not (0 <= ri < len(rooms)):
                    continue
                rname, boxes = rooms[ri]
                names.append(rname)
                for (rx, ry, rw, rh) in boxes:
                    ax, ay = ox + rx, oy + ry
                    minx = ax if minx is None else min(minx, ax)
                    miny = ay if miny is None else min(miny, ay)
                    maxx, maxy = max(maxx, ax + rw), max(maxy, ay + rh)
            if minx is None or not names:
                continue
            rooms_total += len(names)
            out.append((minx, miny, maxx, maxy, names))

    with (dest / "map.lua").open("w", encoding="utf-8") as f:
        f.write("-- The shipped map's real buildings, from .lotheader.\n")
        f.write("-- Generated by tools/sweep/world.py.\n")
        f.write("_G.__BUILDINGS = {\n")
        for k, (a, b, c, d, names) in enumerate(out):
            f.write('  { id = %d, minX = %d, minY = %d, maxX = %d,'
                    ' maxY = %d, rooms = { %s } },\n'
                    % (k + 1, a, b, c, d,
                       ", ".join('"%s"' % n for n in names)))
        f.write("}\n")

    inside = covered(out, coords)
    return {
        "towns": len(found), "points": len(coords), "cells": cells_read,
        "buildings": len(out), "rooms": rooms_total,
        "pointsInABuilding": inside,
    }


def covered(buildings, coords):
    """How many spawn points land inside an extracted building.

    The check that establishes the cell size. It is reported rather
    than asserted: the sweep says what it read and the reader decides,
    which is the same posture the sweep itself takes.
    """
    n = 0
    for (x, y) in coords:
        for (a, b, c, d, _names) in buildings:
            if a <= x < c and b <= y < d:
                n += 1
                break
    return n
