#!/usr/bin/env python3
r"""Border 73 - a binary nobody can regenerate is a binary nobody can check.

[B51] finally answered Border 19's standing complaint - `no icon,
poster`, reported on every run of the gate since the day it was
written, which in a load order of two hundred and thirty-four mods is a
blank tile with a name beside it.

The obvious way to answer it is to draw two PNGs and commit them. That
would have left this tree with the only shipped artifact nothing can
check. Every other one has a border: the jar is compared against its
sources, the sandbox options against their translations, the delimited
protocols against their parsers. A PNG dropped in by hand has none, and
the first time somebody opens it in an editor and saves it back -
recompressed, colour-managed, resized by a helpful default - nothing
notices.

So the art is generated by `tools/make_art.py`, from arithmetic, and
this border regenerates it and compares.

WHAT IS COMPARED, AND WHY NOT THE BYTES
---------------------------------------
The decoded pixels, not the file. Two PNGs of identical images differ
in bytes whenever zlib's output differs - a Python upgrade would do it,
and a border that goes red because the compressor got better is a
border people learn to ignore. Decoding both sides and comparing
dimensions and scanlines is the question actually worth asking: is the
shipped image the image the generator draws?

The four shipped copies are compared to each other too. `mod/` and
`mod/42.20/` each carry a pair, because the engine reads the version
directory and the workshop reads the root, and two files that are
supposed to be one file are exactly the pair that drifts.
"""
import pathlib
import struct
import subprocess
import sys
import tempfile
import zlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
MAKER = ROOT / "tools" / "make_art.py"
SHIPPED = (
    ROOT / "mod" / "icon.png",
    ROOT / "mod" / "poster.png",
    ROOT / "mod" / "42.20" / "icon.png",
    ROOT / "mod" / "42.20" / "poster.png",
)


def decode(path):
    """(width, height, pixel bytes) of a truecolour 8-bit PNG.

    Only the shape this generator writes: no interlacing, no palette,
    no filters beyond the per-scanline byte. A file that is not that
    shape returns None, which is itself the finding - it means
    something other than `make_art.py` produced it.
    """
    try:
        blob = path.read_bytes()
    except OSError:
        return None
    if blob[:8] != b"\x89PNG\r\n\x1a\n":
        return None
    i, chunks = 8, {}
    while i + 8 <= len(blob):
        length = struct.unpack(">I", blob[i:i + 4])[0]
        tag = blob[i + 4:i + 8]
        chunks[tag] = chunks.get(tag, b"") + blob[i + 8:i + 8 + length]
        i += 12 + length
    head = chunks.get(b"IHDR")
    if not head or len(head) < 13:
        return None
    width, height, depth, colour = struct.unpack(">IIBB", head[:10])
    if (depth, colour) != (8, 2) or head[12] != 0:
        return None
    try:
        raw = zlib.decompress(chunks.get(b"IDAT", b""))
    except zlib.error:
        return None
    stride = width * 3 + 1
    if len(raw) != stride * height or any(
            raw[y * stride] != 0 for y in range(height)):
        return None
    return width, height, b"".join(
        raw[y * stride + 1:(y + 1) * stride] for y in range(height))


def main():
    faults = []
    print("=" * 74)
    print("A BINARY NOBODY CAN REGENERATE")
    print("=" * 74)

    if not MAKER.exists():
        print()
        print("VERDICT:")
        print("  FAULT: tools/make_art.py is gone, so the shipped art is now "
              "an asset nobody can check rather than a derived artifact")
        return 1

    with tempfile.TemporaryDirectory() as tmp:
        fresh_dir = pathlib.Path(tmp)
        done = subprocess.run(
            [sys.executable, str(MAKER), "--check", str(fresh_dir)],
            capture_output=True, text=True, timeout=600)
        if done.returncode != 0:
            print()
            print("VERDICT:")
            print("  FAULT: the generator refused to run, so nothing was "
                  f"compared: {(done.stderr or done.stdout).strip()[-200:]}")
            return 1
        fresh = {p.name: decode(p) for p in sorted(fresh_dir.glob("*.png"))}

    if not fresh or any(v is None for v in fresh.values()):
        print()
        print("VERDICT:")
        print("  FAULT: the generator produced nothing this border can read, "
              "so a clean verdict here would be about an empty set")
        return 1

    print(f"  images generated : {len(fresh)}  "
          f"({', '.join(f'{n} {v[0]}x{v[1]}' for n, v in sorted(fresh.items()))})")
    print(f"  shipped copies   : {len(SHIPPED)}")

    for path in SHIPPED:
        rel = path.relative_to(ROOT).as_posix()
        want = fresh.get(path.name)
        if want is None:
            faults.append(
                f"{rel} is shipped and the generator does not draw a "
                f"`{path.name}` - so this file came from somewhere else")
            continue
        got = decode(path)
        if got is None:
            faults.append(
                f"{rel} is missing, or is not the 8-bit truecolour PNG this "
                "generator writes. Either it was never shipped, or something "
                "other than `make_art.py` produced it - an editor's save, a "
                "resize, a colour profile - and the file in the repository "
                "is no longer the file anybody can reproduce")
            continue
        if got[:2] != want[:2]:
            faults.append(
                f"{rel} is {got[0]}x{got[1]} and the generator draws "
                f"{want[0]}x{want[1]}. A resized icon is the single most "
                "likely way for this to go wrong and the hardest to see")
            continue
        if got[2] != want[2]:
            differing = sum(1 for a, b in zip(got[2], want[2]) if a != b)
            faults.append(
                f"{rel} differs from what `make_art.py` draws, in "
                f"{differing} of {len(want[2])} colour bytes. Either the "
                "file was edited by hand - in which case the generator is "
                "now a lie about where the art came from - or the generator "
                "was changed and `python tools/make_art.py` was not re-run")
            continue
        print(f"     {rel:<28} {got[0]}x{got[1]}  matches the generator")

    print()
    print("VERDICT:")
    if faults:
        for f in faults:
            print(f"  FAULT: {f}")
        return 1
    print(f"  73) art derived: all {len(SHIPPED)} shipped images are the "
          "pixels tools/make_art.py draws, so the mod's own art is "
          "reproducible rather than an asset that happens to be here")
    return 0


if __name__ == "__main__":
    sys.exit(main())
