#!/usr/bin/env bash
# Build the SAO Java agent jar. Plain javac + jar; no Gradle until the
# component earns it.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
JDK="/c/Users/jleyv/Peanut Butter/JetBrains/Java/bin"
PZ_JAR="C:/Program Files (x86)/Steam/steamapps/common/ProjectZomboid/projectzomboid.jar"
ZB_JAR="C:/Program Files (x86)/Steam/steamapps/common/ProjectZomboid/ZombieBuddy.jar"
OUT="$ROOT/java/out"
DIST="$ROOT/java/dist"

rm -rf "$OUT" && mkdir -p "$OUT" "$DIST"

# [B43] The version the jar reports is STAMPED, not typed. SAOBridge
# carried a hardcoded "0.1.0.0-pre-alpha+java2" while VERSION said
# 0.6.0.0-pre-alpha - five minor versions apart, and nobody noticed
# because getVersion() was the one bridge method no Lua ever called.
# Generated here from VERSION so the two cannot drift again, into the
# build output rather than the source tree, so a stamp never shows up
# as a dirty working file.
GEN="$OUT/gen/com/sao"
mkdir -p "$GEN"
SAO_VERSION="$(tr -d ' \t\r\n' < "$ROOT/VERSION")"
cat > "$GEN/SAOVersion.java" <<EOF
package com.sao;

/** Generated by tools/build-java.sh from the repository VERSION file.
 *  Do not edit: it is rewritten on every build, and Border 42 checks
 *  the shipped bytecode against VERSION. */
public final class SAOVersion {
    public static final String VALUE = "$SAO_VERSION";
    private SAOVersion() {}
}
EOF
echo "[build] stamped version $SAO_VERSION"

echo "[build] compiling against projectzomboid.jar"
{ find "$ROOT/java/src" -name '*.java'; echo "$GEN/SAOVersion.java"; } \
    | while read -r f; do cygpath -m "$f"; done \
    | sed 's|.*|"&"|' > "$OUT/sources.txt"
"$JDK/javac.exe" -cp "$PZ_JAR;$ZB_JAR" -d "$OUT" "@$OUT/sources.txt"

cat > "$OUT/MANIFEST.MF" <<'EOF'
Manifest-Version: 1.0
Premain-Class: com.sao.agent.SAOAgent
Agent-Class: com.sao.agent.SAOAgent
EOF

echo "[build] packaging SAOAgent.jar"
rm -f "$DIST/SAOAgent.jar"
"$JDK/jar.exe" --create --file "$DIST/SAOAgent.jar" --manifest "$OUT/MANIFEST.MF" -C "$OUT" com

# [B33] The jar also lands in the mod tree, which is the SHIPPING
# location: deploy copies mod/ wholesale, and publishing IS shipping
# mod/. Before this, the tracked mod/42.20/media/java/SAO.jar was a
# separate artifact that nothing rebuilt - two days stale and missing
# all seventeen engine classes the bridge calls. deploy.sh overwrote
# it on the way to the game, so the LIVE install was always correct
# and the defect was invisible from inside a play session. Anyone
# installing from the repository would have got a mod that loads,
# appears to run, and does nothing: NoClassDefFoundError on every
# bridge call, swallowed by the pcall that wraps it.
MODJAR="$ROOT/mod/42.20/media/java/SAO.jar"
mkdir -p "$(dirname "$MODJAR")"
cp "$DIST/SAOAgent.jar" "$MODJAR"

"$JDK/jar.exe" --list --file "$DIST/SAOAgent.jar"
echo "[build] done: $DIST/SAOAgent.jar"
echo "[build] shipped: $MODJAR"
