#!/usr/bin/env bash
# Build the SAO Java agent jar. Plain javac + jar; no Gradle until the
# component earns it.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
JDK="/c/Users/jleyv/Peanut Butter/JetBrains/Java/bin"
if [ ! -x "$JDK/javac.exe" ] \
    && [ -x "/mnt/c/Users/jleyv/Peanut Butter/JetBrains/Java/bin/javac.exe" ]; then
    JDK="/mnt/c/Users/jleyv/Peanut Butter/JetBrains/Java/bin"
fi
PZ_JAR="C:/Program Files (x86)/Steam/steamapps/common/ProjectZomboid/projectzomboid.jar"
ZB_JAR="C:/Program Files (x86)/Steam/steamapps/common/ProjectZomboid/ZombieBuddy.jar"
VIEWPOINT_JAR="$ROOT/vendor/viewpoint/Viewpoint-0.1.5a-hotfix.jar"
VIEWPOINT_SHA256="94FEDDA302AB6C17BA1B38495789E4C9781D52823FB8204214C85402E3CAB41F"
VIEWPOINT_LICENSE_SHA256="F127293CC98E1845BA180E8696B2C23FB93444A929F2B43EB8267728B6F77C74"
OUT="$ROOT/java/out"
DIST="$ROOT/java/dist"

for document in LICENSE CREDITS.md; do
    if [ ! -f "$ROOT/$document" ]; then
        echo "[build] missing required package document: $document" >&2
        exit 1
    fi
done
if [ ! -f "$ROOT/vendor/viewpoint/LICENSE" ] \
    || [ "$(sha256sum "$ROOT/vendor/viewpoint/LICENSE" | awk '{print toupper($1)}')" \
        != "$VIEWPOINT_LICENSE_SHA256" ]; then
    echo "[build] pinned Viewpoint source license missing or changed" >&2
    exit 1
fi

rm -rf "$OUT" && mkdir -p "$OUT" "$DIST"

# [B43] The version the jar reports is STAMPED, not typed. SAOBridge
# carried a hardcoded "0.1.0.0-pre-alpha+java2" while VERSION said
# 0.6.0.0-pre-alpha - five minor versions apart, and nobody noticed
# because getVersion() was the one bridge method no Lua ever called.
# Generated here from VERSION so the two cannot drift again, into the
# build output rather than the source tree, so a stamp never shows up
# as a dirty working file.
GEN="$OUT/gen/com/sao"
mkdir -p "$GEN"
SAO_VERSION="$(tr -d ' \t\r\n' < "$ROOT/VERSION")"
cat > "$GEN/SAOVersion.java" <<EOF
package com.sao;

/** Generated by tools/build-java.sh from the repository VERSION file.
 *  Do not edit: it is rewritten on every build, and Border 42 checks
 *  the shipped bytecode against VERSION. */
public final class SAOVersion {
    public static final String VALUE = "$SAO_VERSION";
    private SAOVersion() {}
}
EOF
echo "[build] stamped version $SAO_VERSION"

echo "[build] compiling against projectzomboid.jar"
to_windows_path() {
    if command -v cygpath > /dev/null 2>&1; then
        cygpath -m "$1"
    else
        # Git Bash normally supplies cygpath, but a POSIX shell started
        # from Windows can still have the same /c/ path shape without it.
        # javac.exe accepts C:/... paths directly.
        printf '%s\n' "$1" | sed -E \
            -e 's|^/mnt/([[:alpha:]])/|\1:/|' \
            -e 's|^/([[:alpha:]])/|\1:/|'
    fi
}
WIN_OUT="$(to_windows_path "$OUT")"
WIN_DIST="$(to_windows_path "$DIST")"
WIN_VIEWPOINT="$(to_windows_path "$VIEWPOINT_JAR")"

# The renderer and shader resources are one pinned Workshop source. Reject
# changed or unexpected archive content before extracting into generated out/.
if [ ! -f "$VIEWPOINT_JAR" ]; then
    echo "[build] missing pinned Viewpoint source: $VIEWPOINT_JAR" >&2
    exit 1
fi
ACTUAL_VIEWPOINT_SHA256="$(sha256sum "$VIEWPOINT_JAR" | awk '{print toupper($1)}')"
if [ "$ACTUAL_VIEWPOINT_SHA256" != "$VIEWPOINT_SHA256" ]; then
    echo "[build] pinned Viewpoint hash mismatch" >&2
    exit 1
fi
if ! "$JDK/jar.exe" --list --file "$WIN_VIEWPOINT" | awk '
    { sub(/\r$/, "") }
    /^viewpoint\// {
        if ($0 ~ /\\/ || $0 ~ /(^|\/)\.\.?(\/|$)/) bad=1
        entries++
        next
    }
    $0 != "META-INF/" && $0 != "META-INF/MANIFEST.MF" { bad=1 }
    END { if (bad || entries != 825) exit 1 }
'; then
    echo "[build] pinned Viewpoint archive entries changed" >&2
    exit 1
fi
(cd "$OUT" && "$JDK/jar.exe" --extract --file "$WIN_VIEWPOINT" viewpoint)
python3 "$ROOT/tools/adapt_viewpoint_framecaps.py" "$OUT/viewpoint/game/FrameCaps.class"

{ find "$ROOT/java/src" -name '*.java'; echo "$GEN/SAOVersion.java"; } \
    | while read -r f; do to_windows_path "$f"; done \
    | sed 's|.*|"&"|' > "$OUT/sources.txt"
"$JDK/javac.exe" -cp "$PZ_JAR;$ZB_JAR;$WIN_VIEWPOINT" -d "$WIN_OUT" \
    "@$WIN_OUT/sources.txt"

# [C82] Native learned artifacts are classpath resources, so inference does
# not depend on a working directory or an external runtime.  Speakeasy owns
# their export; the tracked SAO copy is content-hash checked by the reader.
if [ -d "$ROOT/java/resources" ]; then
    cp -R "$ROOT/java/resources/." "$OUT/"
fi

cat > "$OUT/MANIFEST.MF" <<'EOF'
Manifest-Version: 1.0
Premain-Class: com.sao.agent.SAOAgent
Agent-Class: com.sao.agent.SAOAgent
Can-Retransform-Classes: true
Can-Redefine-Classes: true
EOF

echo "[build] packaging SAOAgent.jar"
rm -f "$DIST/SAOAgent.jar"
"$JDK/jar.exe" --create --file "$WIN_DIST/SAOAgent.jar" \
    --manifest "$WIN_OUT/MANIFEST.MF" -C "$WIN_OUT" com -C "$WIN_OUT" viewpoint

# [B33] The jar also lands in the mod tree, which is the SHIPPING
# location: deploy copies mod/ wholesale, and publishing IS shipping
# mod/. Before this, the tracked mod/42.20/media/java/SAO.jar was a
# separate artifact that nothing rebuilt - two days stale and missing
# all seventeen engine classes the bridge calls. deploy.sh overwrote
# it on the way to the game, so the LIVE install was always correct
# and the defect was invisible from inside a play session. Anyone
# installing from the repository would have got a mod that loads,
# appears to run, and does nothing: NoClassDefFoundError on every
# bridge call, swallowed by the pcall that wraps it.
MODJAR="$ROOT/mod/42.20/media/java/SAO.jar"
mkdir -p "$(dirname "$MODJAR")"
cp "$DIST/SAOAgent.jar" "$MODJAR"

# The mod/ tree is the installable package, so its license and source credit
# travel with the bundled Viewpoint classes and the rest of SAO's sources.
for document in LICENSE CREDITS.md; do
    if ! cmp -s "$ROOT/$document" "$ROOT/mod/$document"; then
        cp "$ROOT/$document" "$ROOT/mod/$document"
    fi
done
if ! cmp -s "$ROOT/vendor/viewpoint/LICENSE" "$ROOT/mod/VIEWPOINT-LICENSE.txt"; then
    cp "$ROOT/vendor/viewpoint/LICENSE" "$ROOT/mod/VIEWPOINT-LICENSE.txt"
fi

echo "[build] packaged SAO classes and pinned Viewpoint renderer/resources"
echo "[build] done: $DIST/SAOAgent.jar"
echo "[build] shipped: $MODJAR"
