CHECKS=0
function check(v,name)CHECKS=CHECKS+1;assert(v,'D2_RESIDUAL:'..name)end
function near(a,b)return math.abs(a-b)<0.0001 end
if MODE=='debug' then
 AMBT={foreign=true};Key={foreign=true}
 local a=LSDebugConfirm:new(0,0,320,260,A,{4},'skill');local b=LSDebugConfirm:new(0,0,320,260,B,{7},'other')
 check(a.ogAmbt==nil and a.key==nil,'debug_unused_copied_globals_absent');check(a.value==4 and b.value==7 and a.character==A and b.character==B,'debug_instance_arguments');check(AMBT.foreign and Key.foreign,'debug_foreign_identity')
elseif MODE=='playlist' or MODE=='wardrobe' or MODE=='soundboard' then
 new={foreign=true};target={foreign=true};onclick={foreign=true}
 local class,o,p
 if MODE=='playlist' then class=PlaylistImportConfirm;o=class:new(1,{'Bnew'},1);p=class:new(0,{'Anew'},1)
 elseif MODE=='wardrobe' then class=WardrobeConfirm;o=class:new(B,1,'Bclothes');p=class:new(A,0,'Aclothes')
 else class=DJSoundboardOverlay;SCENE_SQUARE=nil;local booth={data={}};function booth:getModData()return self.data end;function booth:getX()return 0 end;function booth:getY()return 0 end;function booth:getZ()return 0 end;function booth:getSprite()return{getName=function()return'booth'end}end;o=class:new(B,booth);p=class:new(A,booth)end
 check(o.new==class.new and p.new==class.new,'constructor_inherits_owned_new');check(o.target==nil and o.onclick==nil,'constructor_unbound_callback_fields_absent');check(o.character==B and p.character==A,'constructor_multiple_actor_captures');check(new.foreign and target.foreign and onclick.foreign,'constructor_foreign_globals_preserved')
 if MODE=='playlist' then
  o:initialise();check(o.textlabelPlaylist.label=='B','playlist_selected_initialise');PLAYERS[1]=actor('C');o:onClick({internal='Confirm'});check(B.data.LSJukeboxCustomPlaylist[1].songs[1]=='Bnew' and A.data.LSJukeboxCustomPlaylist[1].songs[1]=='A','playlist_selected_instance_write');check(HALOS[1][1]==B and HALOS[2][1]==B,'playlist_selected_halo_receiver');check(o.removed and not p.removed,'playlist_instance_close');p:onClick({internal='Confirm'});check(A.data.LSJukeboxCustomPlaylist[1].songs[1]=='Anew','playlist_second_instance_write')
 end
elseif MODE=='interaction' then
 adjObj={sprite='foreign'};local get=nativeLocal('getObj');local a={sprite='a'};local b={sprite='b'};local square={getObjects=function()return list({a,b})end}
 check(get(square,'b')==b,'interaction_actual_loop_recipient');check(get(square,'a')==a,'interaction_second_call');check(get(square,'missing')==false,'interaction_missing');local nested;LSUtil.getObjSpriteName=function(obj)if not nested then nested=true;check(get(square,'b')==b,'interaction_native_reentry')end;return obj.sprite end;check(get(square,'a')==a,'interaction_reentrant_outer_recipient');check(adjObj.sprite=='foreign','interaction_foreign_owner')
elseif MODE=='beauty' then
 beauty={foreign=true};loadCustomBeautyTable();loadCustomBeautyTable();check(beauty.foreign,'beauty_foreign_global_preserved');check(nativeEventCount('OnGameStart')==1,'beauty_native_registration');check(getBeautyProperty('carpentry_02_58')==-5 and getBeautyProperty('constructedobjects_01_86')==2,'beauty_owned_scale_exact_rounding_once');check(getBeautyProperty('fixture')==7,'beauty_custom_value_preserved')
elseif MODE=='server-bag' then
 bad=nil;local wanted=nativeItem('wanted');local bag=nativeBag();A.inv:AddItem(nativeItem('decoy'));A.inv:AddItem(bag);bag:setContainer(A.inv);local nativeInv=A.inv
check(bag:getContainer()==nativeInv and bag:getItemContainer()~=nativeInv,'native_bag_parent_vs_contents')
-- Actual source provider ordinarily searches recursively. Named late-arrival control
-- adds the item after its outer native search returned nil, before the fallback scan.
A.inv={getItems=function()return nativeInv:getItems()end,getFirstEvalRecurse=function(_,predicate)local found=nativeInv:getFirstEvalRecurse(predicate);if not found then bag:getItemContainer():AddItem(wanted)end;return found end}
local provider=LSSync.getItemServer;local searched={};LSSync.getItemServer=function(id,cont)searched[#searched+1]=cont;return provider(id,cont)end;LSSync.transmitItemMovData=function(i,p)TRANSFERRED={i,p}end
check(nativeEventCount('OnClientCommand')==1,'server_native_event_registration');nativeEmitCommand('SyncItemData_FromPlayer',A,{wanted:getID()});check(searched[2]==bag:getItemContainer(),'server_fallback_exact_native_bag_contents_provider');check(TRANSFERRED and TRANSFERRED[1]==wanted and TRANSFERRED[2]==A,'server_late_arrival_native_bag_exact_item');TRANSFERRED=nil;nativeEmitCommand('SyncItemData_FromPlayer',B,{wanted:getID()});check(TRANSFERRED==nil,'server_second_actor_no_foreign_item');A.inv=nativeInv;nativeEmitCommand('SyncItemData_FromPlayer',A,{wanted:getID()});check(TRANSFERRED and TRANSFERRED[1]==wanted,'server_ordinary_recursive_provider');check(bad==nil,'server_bad_global_preserved')
elseif MODE=='server-wet' then
 mood='foreign';A.stats=nativeStats();A.body=nativeBody();B.stats=nativeStats();B.body=nativeBody()
 for _,row in ipairs({{'set',30,30},{'add',10,40},{'remove',5,35}})do nativeEmitCommand('ChangeCharacterMood',A,{row[1],'WETNESS',row[2]});local parts=A.body:getBodyParts();check(parts:size()>0,'native_body_parts_exist');for i=0,parts:size()-1 do check(near(parts:get(i):getWetness(),row[3]),'wetness_exact_native_part_'..i)end end
 check(near(A.stats:get(CharacterStat.WETNESS),35),'wetness_native_stat');check(near(B.body:getBodyParts():get(0):getWetness(),0),'wetness_other_actor_unchanged');nativeEmitCommand('ChangeCharacterMood',B,{'set','WETNESS',70});check(near(B.body:getBodyParts():get(0):getWetness(),70) and near(A.body:getBodyParts():get(0):getWetness(),35),'wetness_second_actor');check(mood=='foreign','wetness_foreign_global_preserved')
elseif MODE=='server-movable' then
 movableData={foreign=true};local obj={data={keep=9},getSpriteName=function()return'obj'end};function obj:getModData()return self.data end;function obj:transmitModData()self.sent=true end
 SCENE_SQUARE={getObjects=function()return list({obj})end};nativeEmitCommand('ModifyObjData',A,{{1,2,0,'obj'},{art=4},{ordinary=5}});check(obj.data.movableData and obj.data.movableData.art==4,'movable_exact_argument_merge');check(obj.data.ordinary==5 and obj.data.keep==9,'movable_ordinary_data_preserved');nativeEmitCommand('ModifyObjData',B,{{1,2,0,'obj'},{next=7},nil});check(obj.data.movableData.art==4 and obj.data.movableData.next==7,'movable_second_call_merge');check(movableData.foreign,'movable_foreign_owner')
elseif MODE=='server-trait' then
 traitName='foreign';nativeEmitCommand('ChangeTrait',A,{'BRAVE','add'});check(A.traits:get(CharacterTrait.BRAVE),'trait_native_add');check(A.xpArg==CharacterTrait.BRAVE and A.xpValue==12,'trait_native_xp_exact_argument');check(XP_SENT==A,'trait_sync_owner');nativeEmitCommand('ChangeTrait',A,{'BRAVE','remove'});check(not A.traits:get(CharacterTrait.BRAVE) and A.xpValue==8,'trait_native_remove');check(not B.traits:get(CharacterTrait.BRAVE),'trait_second_actor_unchanged');check(traitName=='foreign','trait_foreign_owner')
elseif MODE=='server-puddle' then
 targetFloor={foreign=true};local actual=nativeSquare();local object;IsoObject.new=function(square,sprite)object=nativePuddle(square,sprite);return object end
 LSServerCommandHandler('CreateDirtPuddle',{actual,false,'dirt'});check(actual:nativeCount()==1 and actual:nativeOwns(object),'puddle_actual_native_constructor_square');check(targetFloor.foreign,'puddle_foreign_owner');local second={setOverlaySprite=function(self,s)self.sprite=s end,transmitUpdatedSpriteToClients=function(self)self.sent=true end};LSServerCommandHandler('CreateDirtPuddle',{second,true,'overlay'});check(second.sprite=='overlay' and second.sent,'puddle_overlay_branch_preserved')
elseif MODE=='harvester' then
 tA={data={cooldown=true}};local a=setmetatable({character=A,item=nativeItem('harvester'),ogFuel=1,data={fuelUses=2,cooldown=false},action={forceStop=function()STOPPED=(STOPPED or 0)+1 end}},LSInvHarvesterAction);a.item:setCondition(10);a:stop();check(TRANSMITTED[1]==a.item and STOPPED==1,'harvester_self_data_and_base_stop');a.data.cooldown=true;a:stop();check(#TRANSMITTED==1 and STOPPED==2,'harvester_own_cooldown');local b=setmetatable({character=B,item=nativeItem('other'),ogFuel=2,data={fuelUses=2},action=a.action},LSInvHarvesterAction);b:stop();check(#TRANSMITTED==1,'harvester_unchanged_fuel');check(tA.data.cooldown,'harvester_foreign_owner')
elseif MODE=='weapon' then
 weapon=nativeWeapon();WeaponType={UNARMED=WeaponType.UNARMED,getWeaponType=function(c)return nativeWeaponType(c.primary)end}
 check(LSUtil.isBareHands(A),'barehands_ignores_foreign_weapon');A.primary=nativeWeapon();check(not LSUtil.isBareHands(A),'barehands_actual_native_handweapon');A.primary=nativeItem('nonweapon');check(LSUtil.isBareHands(A),'barehands_native_nonweapon');check(not LSUtil.isBareHands(nil),'barehands_missing_actor');check(weapon~=A.primary,'barehands_foreign_owner')
elseif MODE=='read' then
 invData={efficiencyMult={0,999},fastRead=true};local state=0;local data={invData={efficiencyMult={0,2},fastRead=true}};HAT={getType=function()return'NeuralHat'end,getVisual=function()return{getTextureChoice=function()return state end}end,getModData=function()return data end}
 local a=setmetatable({character=A,item=nativeBook(),minutesPerPage=1},ISReadABook);state=0;local base=a:getDuration();check(base>=100,'read_native_base_executed')
 local factors={[0]=1,[1]=0.225,[2]=4,[3]=0.35,[4]=0.25,[5]=0.15,[6]=1}
 for i=0,6 do state=i;check(near(a:getDuration(),base*factors[i]),'read_state_'..i)end
 state=1;data.invData.fastRead=false;check(near(a:getDuration(),base*.45),'read_no_fastRead');state=3;data.invData.fastRead=true;check(near(a:getDuration(),base*.35),'read_overdrive_ignores_fastRead');for _,bad in ipairs({false,{}, {efficiencyMult={0,0}},{efficiencyMult={0,'invalid'}},{efficiencyMult=false}})do data.invData=bad;check(near(a:getDuration(),base),'read_invalid_data_base')end;check(invData.efficiencyMult[2]==999,'read_foreign_owner')
elseif MODE=='toilet' then
 containsItem=false;local item=nativeItem('Tissue');local used=0;LSUtil.useItem=function(i,c)check(i==item and c==A,'toilet_exact_use_recipient');used=used+1 end
 LSHygiene.TF.useTP(A,item,nil);check(used==1,'toilet_use_route_preserved');for _,s in ipairs(LOGS)do check(not s:find('not containsItem'),'toilet_obsolete_diagnostic_absent')end;check(containsItem==false,'toilet_foreign_owner')
elseif MODE=='new-menu' or MODE=='vanilla-menu' then
 worldobjects={foreign=true};local kind=MODE=='new-menu' and'Harmonica' or'GuitarAcoustic';local full=MODE=='new-menu' and'Lifestyle.Harmonica' or'Base.GuitarAcoustic';local class=MODE=='new-menu' and NewInstrumentsContextMenu or VanillaInstrumentsContextMenu
 A.data[kind..'LearnedTracks']=CATALOGUES['TimedActions/PlayHarmonicaTracks'];A.data[kind..'LearnedTracks'][2].level=5;A.data.GuitarALearnedTracks=A.data[kind..'LearnedTracks'];local item={getFullType=function()return full end,getType=function()return kind end,isBroken=function()return false end,isInPlayerInventory=function()return true end,getAttachedSlot=function()return SLOT or -1 end,isEquipped=function()return true end};A.inv={contains=function()return true end};local c=context();class.doInventoryMenu(0,c,{item},item)
 local count=0;local expectedActor=A;local function inspect(menu)for _,o in ipairs(menu.options)do if o.callback==class.onAction or o.callback==class.onDebug then check(o.target==false,'inventory_menu_exact_false_target');check(o.args[1]==expectedActor,'inventory_menu_actor');count=count+1;if o.callback==class.onAction then o.callback(o.target,unpack(o.args));check(QUEUED[#QUEUED].actor==expectedActor and QUEUED[#QUEUED].item==item,'inventory_menu_callback_exact_item')end end end;for _,s in ipairs(menu.subs)do inspect(s)end end;inspect(c);check(count>=3,'inventory_menu_branches_reached');SLOT=1;expectedActor=B;B.data=A.data;B.inv=A.inv;count=0;local hot=context();class.doHotbarMenu(1,hot,{item},item);inspect(hot);check(count>=3,'hotbar_menu_branches_reached');check(worldobjects.foreign,'inventory_menu_foreign_owner')
elseif MODE=='art-menu' then
 worldobjects={foreign=true};local selected={actual=true};local art={data={movableData={artBeauty=3,meltStartTime=100}}};function art:hasModData()return true end;function art:getModData()return self.data end;local c=context();local d=context();ArtCardContextMenu.doBuildMenu(0,c,selected,art,'ice','Sculpture Ice',nil,d);local found=false;for _,s in ipairs(d.subs)do for _,o in ipairs(s.options)do if o.callback then check(o.target==selected,'ice_debug_exact_worldobjects');o.callback(o.target,unpack(o.args));found=true end end end;for _,s in ipairs(c.subs)do for _,o in ipairs(s.options)do if o.callback then check(o.target==selected,'ice_debug_exact_worldobjects');o.callback(o.target,unpack(o.args));found=true end end end;check(found and art.data.movableData.meltStartTime==10 and TRANSMITTED[1]==art,'ice_debug_actual_callback');check(worldobjects.foreign,'ice_debug_foreign_owner')
end
PROVEN=true
