import java.nio.file.*;import java.lang.reflect.*;import java.util.*;
import zombie.GameTime;import zombie.Lua.LuaManager;import zombie.characters.*;import zombie.characters.traits.*;import zombie.characters.BodyDamage.*;import zombie.characters.WornItems.*;import zombie.inventory.*;import zombie.inventory.types.*;import zombie.scripting.objects.*;
import se.krka.kahlua.converter.KahluaConverterManager;import se.krka.kahlua.j2se.J2SEPlatform;import se.krka.kahlua.vm.*;
/** Actual native receiver objects. Player body/scene/UI are explicitly controlled. */
final class ResidualNativeBridge {
 static int nextId=2001;static J2SEPlatform p;static KahluaTable env;static sun.misc.Unsafe unsafe;
 static IdentityHashMap<KahluaTable,InventoryItem> items=new IdentityHashMap<>();static Map<String,ItemBodyLocation> locations=new HashMap<>();
 static void field(Object obj,Class<?> owner,String key,Object value)throws Exception{var f=owner.getDeclaredField(key);f.setAccessible(true);f.set(obj,value);}
 static <T extends InventoryItem>T identified(T i){i.setID(nextId++);return i;}
 static InventoryItem item(Object v){return v instanceof InventoryItem i?i:items.get((KahluaTable)v);}
 static KahluaTable makeup(String name,String loc){var location=locations.computeIfAbsent(loc,k->{var v=ItemBodyLocation.register("sao_residual:"+k);BodyLocations.getGroup("ResidualProof").getOrCreateLocation(v);return v;});var actual=identified(new InventoryItem("Proof",name,name,"Item_None"));var t=p.newTable();items.put(t,actual);t.rawset("getBodyLocation",(JavaFunction)(f,n)->f.push(location));t.rawset("getName",(JavaFunction)(f,n)->f.push(name));t.rawset("getType",(JavaFunction)(f,n)->f.push(name));return t;}
 static KahluaTable inventory(ItemContainer inv){var t=p.newTable();t.rawset("setDrawDirty",(JavaFunction)(f,n)->{inv.setDrawDirty(Boolean.TRUE.equals(f.get(1)));return 0;});t.rawset("AddItem",(JavaFunction)(f,n)->{var i=item(f.get(1));inv.AddItem(i);i.setContainer(inv);return f.push(f.get(1));});t.rawset("contains",(JavaFunction)(f,n)->f.push(inv.contains(item(f.get(1)))));t.rawset("Remove",(JavaFunction)(f,n)->{inv.Remove(item(f.get(1)));return 0;});return t;}
 static int body(LuaCallFrame f){try{var actor=(IsoPlayer)unsafe.allocateInstance(IsoPlayer.class);field(actor,IsoGameCharacter.class,"stats",new Stats());return f.push(new BodyDamage(actor));}catch(Exception e){throw new RuntimeException(e);}}
 static void init(J2SEPlatform platform,KahluaTable environment,KahluaThread thread)throws Exception{
  p=platform;env=environment;var uf=sun.misc.Unsafe.class.getDeclaredField("theUnsafe");uf.setAccessible(true);unsafe=(sun.misc.Unsafe)uf.get(null);
  zombie.GameWindow.gameThread=Thread.currentThread();zombie.core.random.RandStandard.INSTANCE.init();GameTime.setInstance(new GameTime());zombie.ZomboidFileSystem.instance.setCacheDir(Path.of("native-cache").toAbsolutePath().toString());zombie.ZomboidFileSystem.instance.base.set(new java.io.File("."));
  zombie.ui.UIManager.defaultthread=thread;LuaManager.platform=p;LuaManager.converterManager=new KahluaConverterManager();zombie.Lua.KahluaNumberConverter.install(LuaManager.converterManager);LuaManager.exposer=new LuaManager.Exposer(LuaManager.converterManager,p,env);LuaManager.caller=new se.krka.kahlua.integration.LuaCaller(LuaManager.converterManager);
  ResidualBookBridge.init(p,env,thread);
  for(Class<?> c:new Class<?>[]{InventoryItem.class,ItemContainer.class,InventoryContainer.class,DrainableComboItem.class,HandWeapon.class,Literature.class,Stats.class,CharacterStat.class,CharacterTraits.class,CharacterTrait.class,BodyDamage.class,BodyPart.class,java.util.ArrayList.class,ItemBodyLocation.class,ItemTag.class,zombie.iso.IsoObject.class,zombie.iso.IsoGridSquare.class,WeaponType.class,zombie.core.ImmutableColor.class}){LuaManager.exposer.setExposed(c);LuaManager.exposer.exposeLikeJava(c,env);}
  var squares=new IdentityHashMap<KahluaTable,zombie.iso.IsoGridSquare>();
  env.rawset("nativeSquare",(JavaFunction)(f,n)->{var sq=new zombie.iso.IsoGridSquare(null,null,10,20,0);var host=p.newTable();squares.put(host,sq);host.rawset("AddTileObject",(JavaFunction)(q,z)->{sq.getObjects().add((zombie.iso.IsoObject)q.get(1));return 0;});host.rawset("nativeCount",(JavaFunction)(q,z)->q.push((double)sq.getObjects().size()));host.rawset("nativeOwns",(JavaFunction)(q,z)->q.push(((zombie.iso.IsoObject)q.get(1)).getSquare()==sq));return f.push(host);});
  env.rawset("nativePuddle",(JavaFunction)(f,n)->{var sq=squares.get((KahluaTable)f.get(0));if(sq==null)throw new AssertionError("D2_RESIDUAL:puddle_constructor_exact_square");return f.push(new zombie.iso.IsoObject(sq,(String)f.get(1)));});
  env.rawset("nativeContainer",(JavaFunction)(f,n)->f.push(new ItemContainer()));
  env.rawset("nativeBag",(JavaFunction)(f,n)->f.push(identified(new InventoryContainer("Proof","Bag","Bag","Item_None"))));
  env.rawset("nativeItem",(JavaFunction)(f,n)->f.push(identified(new InventoryItem("Base",(String)f.get(0),(String)f.get(0),"Item_None"))));
  env.rawset("nativeNeedle",(JavaFunction)(f,n)->{var script=new Item();var module=new ScriptModule();module.name="Proof";script.setModule(module);script.setName("Needle");var i=new DrainableComboItem("Proof","Needle","Needle",script);i.setUseDelta(.1f);i.setUsedDelta(1f);return f.push(i);});
  env.rawset("nativeMakeup",(JavaFunction)(f,n)->f.push(makeup((String)f.get(0),(String)f.get(1))));
  env.rawset("nativeWearer",(JavaFunction)(f,n)->{var worn=new WornItems(BodyLocations.getGroup("ResidualProof"));var t=p.newTable();var inv=new ItemContainer();var hostInv=inventory(inv);t.rawset("getInventory",(JavaFunction)(q,z)->q.push(hostInv));t.rawset("getWornItem",(JavaFunction)(q,z)->{var actual=worn.getItem((ItemBodyLocation)q.get(1));for(var row:items.entrySet())if(row.getValue()==actual)return q.push(row.getKey());return q.push(null);});t.rawset("setWornItem",(JavaFunction)(q,z)->{worn.setItem((ItemBodyLocation)q.get(1),item(q.get(2)));return 0;});t.rawset("removeWornItem",(JavaFunction)(q,z)->{worn.remove(item(q.get(1)));return 0;});t.rawset("nativeAdd",(JavaFunction)(q,z)->{inv.AddItem(item(q.get(1)));return 0;});t.rawset("nativeContains",(JavaFunction)(q,z)->q.push(inv.contains(item(q.get(1)))));t.rawset("nativeWornCount",(JavaFunction)(q,z)->q.push((double)worn.size()));return f.push(t);});
  env.rawset("nativeBody",(JavaFunction)(f,n)->body(f));
  env.rawset("nativeStats",(JavaFunction)(f,n)->f.push(new Stats()));
  env.rawset("nativeTraits",(JavaFunction)(f,n)->f.push(new CharacterTraits()));
  env.rawset("nativeWeapon",(JavaFunction)(f,n)->{var i=new HandWeapon("Proof","Weapon","Weapon","Item_None");return f.push(i);});
  env.rawset("nativeWeaponType",(JavaFunction)(f,n)->{try{var actor=(IsoPlayer)unsafe.allocateInstance(IsoPlayer.class);field(actor,IsoGameCharacter.class,"gameVariables",new zombie.core.skinnedmodel.advancedanimation.AnimationVariableSource());return f.push(WeaponType.getWeaponType(actor,item(f.get(0)),null));}catch(Exception e){throw new RuntimeException(e);}});
  env.rawset("nativeTraitXP",(JavaFunction)(f,n)->{try{var trait=(CharacterTrait)f.get(0);var remove=Boolean.TRUE.equals(f.get(1));var actor=(IsoPlayer)unsafe.allocateInstance(IsoPlayer.class);var desc=(SurvivorDesc)unsafe.allocateInstance(SurvivorDesc.class);var map=new HashMap<zombie.characters.skills.PerkFactory.Perk,Integer>();map.put(zombie.characters.skills.PerkFactory.Perks.Woodwork,10);field(desc,SurvivorDesc.class,"xpBoostMap",map);field(actor,IsoGameCharacter.class,"descriptor",desc);var def=CharacterTraitDefinition.addCharacterTraitDefinition(trait,"controlled trait metadata",0,"proof",false);def.addXPBoost(zombie.characters.skills.PerkFactory.Perks.Woodwork,2);actor.modifyTraitXPBoost(trait,remove);return f.push((double)map.get(zombie.characters.skills.PerkFactory.Perks.Woodwork));}catch(Exception e){throw new RuntimeException(e);}});
  env.rawset("nativeIs",(JavaFunction)(f,n)->{Object v=f.get(0);String type=(String)f.get(1);return f.push(type.equals("HandWeapon")?v instanceof HandWeapon:type.equals("InventoryItem")?v instanceof InventoryItem:type.equals("InventoryContainer")?v instanceof InventoryContainer:false);});
  env.rawset("nativeBook",(JavaFunction)(f,n)->f.push(zombie.Lua.LuaManager.GlobalObject.instanceItem("Base.Notebook")));
 }
}
